// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSAttachmentInfoResponseMessageType.h"
#import "HEWSArrayOfAttachmentsType.h"

@implementation HEWSAttachmentInfoResponseMessageType

@synthesize attachments = _attachments;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    PicoClassSchema *cs = [[PicoClassSchema alloc] initWithXmlName:@"CreateAttachmentResponseMessage" nsUri:@"http://schemas.microsoft.com/exchange/services/2006/messages"];
    [cs autorelease];
    return cs;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Attachments" propertyName:@"attachments" type:PICO_TYPE_OBJECT clazz:[HEWSArrayOfAttachmentsType class]];
    [map setObject:ps forKey:@"attachments"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.attachments = nil;
    [super dealloc];
}

@end
