// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "HEWSBaseRequestType.h"


@class HEWSStreamingSubscriptionRequestType;
@class HEWSPushSubscriptionRequestType;
@class HEWSPullSubscriptionRequestType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSSubscribeType : HEWSBaseRequestType {

@private
    HEWSPullSubscriptionRequestType *_pullSubscriptionRequest;
    HEWSPushSubscriptionRequestType *_pushSubscriptionRequest;
    HEWSStreamingSubscriptionRequestType *_streamingSubscriptionRequest;

}


/**
 (public property)
 
 type : class HEWSPullSubscriptionRequestType
*/
@property (nonatomic, retain) HEWSPullSubscriptionRequestType *pullSubscriptionRequest;

/**
 (public property)
 
 type : class HEWSPushSubscriptionRequestType
*/
@property (nonatomic, retain) HEWSPushSubscriptionRequestType *pushSubscriptionRequest;

/**
 (public property)
 
 type : class HEWSStreamingSubscriptionRequestType
*/
@property (nonatomic, retain) HEWSStreamingSubscriptionRequestType *streamingSubscriptionRequest;


@end
