// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "HEWSBaseRequestType.h"


@class HEWSUserConfigurationNameType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSDeleteUserConfigurationType : HEWSBaseRequestType {

@private
    HEWSUserConfigurationNameType *_userConfigurationName;

}


/**
 (public property)
 
 type : class HEWSUserConfigurationNameType
*/
@property (nonatomic, retain) HEWSUserConfigurationNameType *userConfigurationName;


@end
