// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class HEWSResponseMessageType;
@class HEWSFreeBusyView;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSFreeBusyResponseType : NSObject <PicoBindable> {

@private
    HEWSResponseMessageType *_responseMessage;
    HEWSFreeBusyView *_freeBusyView;

}


/**
 (public property)
 
 type : class HEWSResponseMessageType
*/
@property (nonatomic, retain) HEWSResponseMessageType *responseMessage;

/**
 (public property)
 
 type : class HEWSFreeBusyView
*/
@property (nonatomic, retain) HEWSFreeBusyView *freeBusyView;


@end
