// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "HEWSBaseRequestType.h"


@class HEWSNonEmptyArrayOfSubscriptionIdsType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSGetStreamingEventsType : HEWSBaseRequestType {

@private
    HEWSNonEmptyArrayOfSubscriptionIdsType *_subscriptionIds;
    NSNumber *_connectionTimeout;

}


/**
 (public property)
 
 type : class HEWSNonEmptyArrayOfSubscriptionIdsType
*/
@property (nonatomic, retain) HEWSNonEmptyArrayOfSubscriptionIdsType *subscriptionIds;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *connectionTimeout;


@end
