// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSRefreshSharingFolderType.h"
#import "HEWSFolderIdType.h"

@implementation HEWSRefreshSharingFolderType

@synthesize sharingFolderId = _sharingFolderId;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    PicoClassSchema *cs = [[PicoClassSchema alloc] initWithXmlName:@"RefreshSharingFolder" nsUri:@"http://schemas.microsoft.com/exchange/services/2006/messages"];
    [cs autorelease];
    return cs;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"SharingFolderId" propertyName:@"sharingFolderId" type:PICO_TYPE_OBJECT clazz:[HEWSFolderIdType class]];
    [map setObject:ps forKey:@"sharingFolderId"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.sharingFolderId = nil;
    [super dealloc];
}

@end
