// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "HEWSResponseMessageType.h"


@class HEWSNonEmptyArrayOfSubscriptionIdsType;
@class HEWSNonEmptyArrayOfNotificationsType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSGetStreamingEventsResponseMessageType : HEWSResponseMessageType {

@private
    HEWSNonEmptyArrayOfNotificationsType *_notifications;
    HEWSNonEmptyArrayOfSubscriptionIdsType *_errorSubscriptionIds;
    NSString *_connectionStatus;

}


/**
 (public property)
 
 type : class HEWSNonEmptyArrayOfNotificationsType
*/
@property (nonatomic, retain) HEWSNonEmptyArrayOfNotificationsType *notifications;

/**
 (public property)
 
 type : class HEWSNonEmptyArrayOfSubscriptionIdsType
*/
@property (nonatomic, retain) HEWSNonEmptyArrayOfSubscriptionIdsType *errorSubscriptionIds;

/**
 (public property)
 
 type: string constant in HEWSConnectionStatusType.h
*/
@property (nonatomic, retain) NSString *connectionStatus;


@end
