// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "HEWSBaseRequestType.h"



/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSGetInboxRulesRequestType : HEWSBaseRequestType {

@private
    NSString *_mailboxSmtpAddress;

}


/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *mailboxSmtpAddress;


@end
