// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSDeleteItemType.h"
#import "HEWSNonEmptyArrayOfBaseItemIdsType.h"

@implementation HEWSDeleteItemType

@synthesize itemIds = _itemIds;
@synthesize deleteType = _deleteType;
@synthesize sendMeetingCancellations = _sendMeetingCancellations;
@synthesize affectedTaskOccurrences = _affectedTaskOccurrences;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    PicoClassSchema *cs = [[PicoClassSchema alloc] initWithXmlName:@"DeleteItem" nsUri:@"http://schemas.microsoft.com/exchange/services/2006/messages"];
    [cs autorelease];
    return cs;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ItemIds" propertyName:@"itemIds" type:PICO_TYPE_OBJECT clazz:[HEWSNonEmptyArrayOfBaseItemIdsType class]];
    [map setObject:ps forKey:@"itemIds"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ATTRIBUTE xmlName:@"DeleteType" propertyName:@"deleteType" type:PICO_TYPE_ENUM clazz:nil];
    [map setObject:ps forKey:@"deleteType"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ATTRIBUTE xmlName:@"SendMeetingCancellations" propertyName:@"sendMeetingCancellations" type:PICO_TYPE_ENUM clazz:nil];
    [map setObject:ps forKey:@"sendMeetingCancellations"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ATTRIBUTE xmlName:@"AffectedTaskOccurrences" propertyName:@"affectedTaskOccurrences" type:PICO_TYPE_ENUM clazz:nil];
    [map setObject:ps forKey:@"affectedTaskOccurrences"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.itemIds = nil;
    self.deleteType = nil;
    self.sendMeetingCancellations = nil;
    self.affectedTaskOccurrences = nil;
    [super dealloc];
}

@end
