// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSFindConversationType.h"
#import "HEWSNonEmptyArrayOfFieldOrdersType.h"
#import "HEWSTargetFolderIdType.h"
#import "HEWSIndexedPageViewType.h"

@implementation HEWSFindConversationType

@synthesize indexedPageItemView = _indexedPageItemView;
@synthesize sortOrder = _sortOrder;
@synthesize parentFolderId = _parentFolderId;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    PicoClassSchema *cs = [[PicoClassSchema alloc] initWithXmlName:@"FindConversation" nsUri:@"http://schemas.microsoft.com/exchange/services/2006/messages"];
    [cs autorelease];
    return cs;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"IndexedPageItemView" propertyName:@"indexedPageItemView" type:PICO_TYPE_OBJECT clazz:[HEWSIndexedPageViewType class]];
    [map setObject:ps forKey:@"indexedPageItemView"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"SortOrder" propertyName:@"sortOrder" type:PICO_TYPE_OBJECT clazz:[HEWSNonEmptyArrayOfFieldOrdersType class]];
    [map setObject:ps forKey:@"sortOrder"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ParentFolderId" propertyName:@"parentFolderId" type:PICO_TYPE_OBJECT clazz:[HEWSTargetFolderIdType class]];
    [map setObject:ps forKey:@"parentFolderId"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.indexedPageItemView = nil;
    self.sortOrder = nil;
    self.parentFolderId = nil;
    [super dealloc];
}

@end
