// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSGetUserOofSettingsRequest.h"
#import "HEWSEmailAddress.h"

@implementation HEWSGetUserOofSettingsRequest

@synthesize mailbox = _mailbox;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    PicoClassSchema *cs = [[PicoClassSchema alloc] initWithXmlName:@"GetUserOofSettingsRequest" nsUri:@"http://schemas.microsoft.com/exchange/services/2006/messages"];
    [cs autorelease];
    return cs;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Mailbox" propertyName:@"mailbox" type:PICO_TYPE_OBJECT clazz:[HEWSEmailAddress class]];
    [map setObject:ps forKey:@"mailbox"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.mailbox = nil;
    [super dealloc];
}

@end
