// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"



/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSArrayOfResponseMessagesType : NSObject <PicoBindable> {

@private
    NSMutableArray *_createItemResponseMessageOrDeleteItemResponseMessageOrGetItemResponseMessage;

}


/**
 (public property)
 
 entry type : class HEWSJAXBElement<? extends ResponseMessageType>
*/

@property (nonatomic, retain) NSMutableArray *createItemResponseMessageOrDeleteItemResponseMessageOrGetItemResponseMessage;


@end
