// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "HEWSResponseMessageType.h"


@class HEWSMailTips;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSMailTipsResponseMessageType : HEWSResponseMessageType {

@private
    HEWSMailTips *_mailTips;

}


/**
 (public property)
 
 type : class HEWSMailTips
*/
@property (nonatomic, retain) HEWSMailTips *mailTips;


@end
