// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"



/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSSendNotificationResultType : NSObject <PicoBindable> {

@private
    NSString *_subscriptionStatus;

}


/**
 (public property)
 
 type: string constant in HEWSSubscriptionStatusType.h
*/
@property (nonatomic, retain) NSString *subscriptionStatus;


@end
