// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "HEWSBaseRequestType.h"


@class HEWSSuggestionsViewOptionsType;
@class HEWSSerializableTimeZone;
@class HEWSArrayOfMailboxData;
@class HEWSFreeBusyViewOptionsType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSGetUserAvailabilityRequestType : HEWSBaseRequestType {

@private
    HEWSSerializableTimeZone *_timeZone;
    HEWSArrayOfMailboxData *_mailboxDataArray;
    HEWSFreeBusyViewOptionsType *_freeBusyViewOptions;
    HEWSSuggestionsViewOptionsType *_suggestionsViewOptions;

}


/**
 (public property)
 
 type : class HEWSSerializableTimeZone
*/
@property (nonatomic, retain) HEWSSerializableTimeZone *timeZone;

/**
 (public property)
 
 type : class HEWSArrayOfMailboxData
*/
@property (nonatomic, retain) HEWSArrayOfMailboxData *mailboxDataArray;

/**
 (public property)
 
 type : class HEWSFreeBusyViewOptionsType
*/
@property (nonatomic, retain) HEWSFreeBusyViewOptionsType *freeBusyViewOptions;

/**
 (public property)
 
 type : class HEWSSuggestionsViewOptionsType
*/
@property (nonatomic, retain) HEWSSuggestionsViewOptionsType *suggestionsViewOptions;


@end
