// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "HEWSResponseMessageType.h"


@class HEWSArrayOfEmailAddressesType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSGetRoomListsResponseMessageType : HEWSResponseMessageType {

@private
    HEWSArrayOfEmailAddressesType *_roomLists;

}


/**
 (public property)
 
 type : class HEWSArrayOfEmailAddressesType
*/
@property (nonatomic, retain) HEWSArrayOfEmailAddressesType *roomLists;


@end
