// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSUpdateItemType.h"
#import "HEWSNonEmptyArrayOfItemChangesType.h"
#import "HEWSTargetFolderIdType.h"

@implementation HEWSUpdateItemType

@synthesize savedItemFolderId = _savedItemFolderId;
@synthesize itemChanges = _itemChanges;
@synthesize conflictResolution = _conflictResolution;
@synthesize messageDisposition = _messageDisposition;
@synthesize sendMeetingInvitationsOrCancellations = _sendMeetingInvitationsOrCancellations;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    PicoClassSchema *cs = [[PicoClassSchema alloc] initWithXmlName:@"UpdateItem" nsUri:@"http://schemas.microsoft.com/exchange/services/2006/messages"];
    [cs autorelease];
    return cs;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"SavedItemFolderId" propertyName:@"savedItemFolderId" type:PICO_TYPE_OBJECT clazz:[HEWSTargetFolderIdType class]];
    [map setObject:ps forKey:@"savedItemFolderId"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ItemChanges" propertyName:@"itemChanges" type:PICO_TYPE_OBJECT clazz:[HEWSNonEmptyArrayOfItemChangesType class]];
    [map setObject:ps forKey:@"itemChanges"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ATTRIBUTE xmlName:@"ConflictResolution" propertyName:@"conflictResolution" type:PICO_TYPE_ENUM clazz:nil];
    [map setObject:ps forKey:@"conflictResolution"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ATTRIBUTE xmlName:@"MessageDisposition" propertyName:@"messageDisposition" type:PICO_TYPE_ENUM clazz:nil];
    [map setObject:ps forKey:@"messageDisposition"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ATTRIBUTE xmlName:@"SendMeetingInvitationsOrCancellations" propertyName:@"sendMeetingInvitationsOrCancellations" type:PICO_TYPE_ENUM clazz:nil];
    [map setObject:ps forKey:@"sendMeetingInvitationsOrCancellations"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.savedItemFolderId = nil;
    self.itemChanges = nil;
    self.conflictResolution = nil;
    self.messageDisposition = nil;
    self.sendMeetingInvitationsOrCancellations = nil;
    [super dealloc];
}

@end
