// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "HEWSBaseRequestType.h"


@class HEWSNonEmptyArrayOfBaseFolderIdsType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSDeleteFolderType : HEWSBaseRequestType {

@private
    HEWSNonEmptyArrayOfBaseFolderIdsType *_folderIds;
    NSString *_deleteType;

}


/**
 (public property)
 
 type : class HEWSNonEmptyArrayOfBaseFolderIdsType
*/
@property (nonatomic, retain) HEWSNonEmptyArrayOfBaseFolderIdsType *folderIds;

/**
 (public property)
 
 type: string constant in HEWSDisposalType.h
*/
@property (nonatomic, retain) NSString *deleteType;


@end
