// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "HEWSResponseMessageType.h"


@class HEWSAlternateIdBaseType;

/**
 
                 Response Message for a single id conversion in the ConvertId web method.  Note
                 that the AlternateId element will be missing in the case of an error.
             
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSConvertIdResponseMessageType : HEWSResponseMessageType {

@private
    HEWSAlternateIdBaseType *_alternateId;

}


/**
 (public property)
 
 type : class HEWSAlternateIdBaseType
*/
@property (nonatomic, retain) HEWSAlternateIdBaseType *alternateId;


@end
