// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSRemoveDelegateType.h"
#import "HEWSArrayOfUserIdType.h"

@implementation HEWSRemoveDelegateType

@synthesize userIds = _userIds;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    PicoClassSchema *cs = [[PicoClassSchema alloc] initWithXmlName:@"RemoveDelegate" nsUri:@"http://schemas.microsoft.com/exchange/services/2006/messages"];
    [cs autorelease];
    return cs;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"UserIds" propertyName:@"userIds" type:PICO_TYPE_OBJECT clazz:[HEWSArrayOfUserIdType class]];
    [map setObject:ps forKey:@"userIds"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.userIds = nil;
    [super dealloc];
}

@end
