// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "HEWSResponseMessageType.h"


@class HEWSNotificationType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSGetEventsResponseMessageType : HEWSResponseMessageType {

@private
    HEWSNotificationType *_notification;

}


/**
 (public property)
 
 type : class HEWSNotificationType
*/
@property (nonatomic, retain) HEWSNotificationType *notification;


@end
