// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "HEWSBaseRequestType.h"


@class HEWSNonEmptyArrayOfFolderChangesType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSUpdateFolderType : HEWSBaseRequestType {

@private
    HEWSNonEmptyArrayOfFolderChangesType *_folderChanges;

}


/**
 (public property)
 
 type : class HEWSNonEmptyArrayOfFolderChangesType
*/
@property (nonatomic, retain) HEWSNonEmptyArrayOfFolderChangesType *folderChanges;


@end
