// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "HEWSResponseMessageType.h"


@class HEWSArrayOfStringsType;
@class HEWSArrayOfTrackingPropertiesType;
@class HEWSMessageTrackingReportType;
@class HEWSArrayOfArraysOfTrackingPropertiesType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSGetMessageTrackingReportResponseMessageType : HEWSResponseMessageType {

@private
    HEWSMessageTrackingReportType *_messageTrackingReport;
    HEWSArrayOfStringsType *_diagnostics;
    HEWSArrayOfArraysOfTrackingPropertiesType *_errors;
    HEWSArrayOfTrackingPropertiesType *_properties;

}


/**
 (public property)
 
 type : class HEWSMessageTrackingReportType
*/
@property (nonatomic, retain) HEWSMessageTrackingReportType *messageTrackingReport;

/**
 (public property)
 
 type : class HEWSArrayOfStringsType
*/
@property (nonatomic, retain) HEWSArrayOfStringsType *diagnostics;

/**
 (public property)
 
 type : class HEWSArrayOfArraysOfTrackingPropertiesType
*/
@property (nonatomic, retain) HEWSArrayOfArraysOfTrackingPropertiesType *errors;

/**
 (public property)
 
 type : class HEWSArrayOfTrackingPropertiesType
*/
@property (nonatomic, retain) HEWSArrayOfTrackingPropertiesType *properties;


@end
