// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "HEWSBaseRequestType.h"


@class HEWSArrayOfRuleOperationsType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSUpdateInboxRulesRequestType : HEWSBaseRequestType {

@private
    NSString *_mailboxSmtpAddress;
    NSNumber *_removeOutlookRuleBlob;
    HEWSArrayOfRuleOperationsType *_operations;

}


/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *mailboxSmtpAddress;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *removeOutlookRuleBlob;

/**
 (public property)
 
 type : class HEWSArrayOfRuleOperationsType
*/
@property (nonatomic, retain) HEWSArrayOfRuleOperationsType *operations;


@end
