// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "HEWSResponseMessageType.h"


@class HEWSPhoneCallIdType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSPlayOnPhoneResponseMessageType : HEWSResponseMessageType {

@private
    HEWSPhoneCallIdType *_phoneCallId;

}


/**
 (public property)
 
 type : class HEWSPhoneCallIdType
*/
@property (nonatomic, retain) HEWSPhoneCallIdType *phoneCallId;


@end
