// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSFindMailboxStatisticsByKeywordsResponseMessageType.h"
#import "HEWSMailboxStatisticsSearchResultType.h"

@implementation HEWSFindMailboxStatisticsByKeywordsResponseMessageType

@synthesize mailboxStatisticsSearchResult = _mailboxStatisticsSearchResult;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    PicoClassSchema *cs = [[PicoClassSchema alloc] initWithXmlName:@"FindMailboxStatisticsByKeywordsResponseMessage" nsUri:@"http://schemas.microsoft.com/exchange/services/2006/messages"];
    [cs autorelease];
    return cs;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"MailboxStatisticsSearchResult" propertyName:@"mailboxStatisticsSearchResult" type:PICO_TYPE_OBJECT clazz:[HEWSMailboxStatisticsSearchResultType class]];
    [map setObject:ps forKey:@"mailboxStatisticsSearchResult"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.mailboxStatisticsSearchResult = nil;
    [super dealloc];
}

@end
