// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSGetMessageTrackingReportResponseMessageType.h"
#import "HEWSArrayOfStringsType.h"
#import "HEWSArrayOfTrackingPropertiesType.h"
#import "HEWSMessageTrackingReportType.h"
#import "HEWSArrayOfArraysOfTrackingPropertiesType.h"

@implementation HEWSGetMessageTrackingReportResponseMessageType

@synthesize messageTrackingReport = _messageTrackingReport;
@synthesize diagnostics = _diagnostics;
@synthesize errors = _errors;
@synthesize properties = _properties;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    PicoClassSchema *cs = [[PicoClassSchema alloc] initWithXmlName:@"GetMessageTrackingReportResponse" nsUri:@"http://schemas.microsoft.com/exchange/services/2006/messages"];
    [cs autorelease];
    return cs;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"MessageTrackingReport" propertyName:@"messageTrackingReport" type:PICO_TYPE_OBJECT clazz:[HEWSMessageTrackingReportType class]];
    [map setObject:ps forKey:@"messageTrackingReport"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Diagnostics" propertyName:@"diagnostics" type:PICO_TYPE_OBJECT clazz:[HEWSArrayOfStringsType class]];
    [map setObject:ps forKey:@"diagnostics"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Errors" propertyName:@"errors" type:PICO_TYPE_OBJECT clazz:[HEWSArrayOfArraysOfTrackingPropertiesType class]];
    [map setObject:ps forKey:@"errors"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Properties" propertyName:@"properties" type:PICO_TYPE_OBJECT clazz:[HEWSArrayOfTrackingPropertiesType class]];
    [map setObject:ps forKey:@"properties"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.messageTrackingReport = nil;
    self.diagnostics = nil;
    self.errors = nil;
    self.properties = nil;
    [super dealloc];
}

@end
