// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "HEWSBaseRequestType.h"


@class HEWSUserConfigurationNameType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSGetUserConfigurationType : HEWSBaseRequestType {

@private
    HEWSUserConfigurationNameType *_userConfigurationName;
    NSMutableArray *_userConfigurationProperties;

}


/**
 (public property)
 
 type : class HEWSUserConfigurationNameType
*/
@property (nonatomic, retain) HEWSUserConfigurationNameType *userConfigurationName;

/**
 (public property)
 
 entry type : NSString, wrapper for primitive string
*/

@property (nonatomic, retain) NSMutableArray *userConfigurationProperties;


@end
