// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "HEWSBaseRequestType.h"


@class HEWSUserOofSettings;
@class HEWSEmailAddress;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSSetUserOofSettingsRequest : HEWSBaseRequestType {

@private
    HEWSEmailAddress *_mailbox;
    HEWSUserOofSettings *_userOofSettings;

}


/**
 (public property)
 
 type : class HEWSEmailAddress
*/
@property (nonatomic, retain) HEWSEmailAddress *mailbox;

/**
 (public property)
 
 type : class HEWSUserOofSettings
*/
@property (nonatomic, retain) HEWSUserOofSettings *userOofSettings;


@end
