// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSEmptyFolderType.h"
#import "HEWSNonEmptyArrayOfBaseFolderIdsType.h"

@implementation HEWSEmptyFolderType

@synthesize folderIds = _folderIds;
@synthesize deleteType = _deleteType;
@synthesize deleteSubFolders = _deleteSubFolders;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    PicoClassSchema *cs = [[PicoClassSchema alloc] initWithXmlName:@"EmptyFolder" nsUri:@"http://schemas.microsoft.com/exchange/services/2006/messages"];
    [cs autorelease];
    return cs;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"FolderIds" propertyName:@"folderIds" type:PICO_TYPE_OBJECT clazz:[HEWSNonEmptyArrayOfBaseFolderIdsType class]];
    [map setObject:ps forKey:@"folderIds"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ATTRIBUTE xmlName:@"DeleteType" propertyName:@"deleteType" type:PICO_TYPE_ENUM clazz:nil];
    [map setObject:ps forKey:@"deleteType"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ATTRIBUTE xmlName:@"DeleteSubFolders" propertyName:@"deleteSubFolders" type:PICO_TYPE_BOOL clazz:nil];
    [map setObject:ps forKey:@"deleteSubFolders"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.folderIds = nil;
    self.deleteType = nil;
    self.deleteSubFolders = nil;
    [super dealloc];
}

@end
