// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "HEWSBaseRequestType.h"


@class HEWSNonEmptyArrayOfFolderNamesType;
@class HEWSEmailAddressType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSCreateManagedFolderRequestType : HEWSBaseRequestType {

@private
    HEWSNonEmptyArrayOfFolderNamesType *_folderNames;
    HEWSEmailAddressType *_mailbox;

}


/**
 (public property)
 
 type : class HEWSNonEmptyArrayOfFolderNamesType
*/
@property (nonatomic, retain) HEWSNonEmptyArrayOfFolderNamesType *folderNames;

/**
 (public property)
 
 type : class HEWSEmailAddressType
*/
@property (nonatomic, retain) HEWSEmailAddressType *mailbox;


@end
