// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "HEWSBaseDelegateResponseMessageType.h"



/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSGetDelegateResponseMessageType : HEWSBaseDelegateResponseMessageType {

@private
    NSString *_deliverMeetingRequests;

}


/**
 (public property)
 
 type: string constant in HEWSDeliverMeetingRequestsType.h
*/
@property (nonatomic, retain) NSString *deliverMeetingRequests;


@end
