// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSServiceConfigurationResponseMessageType.h"
#import "HEWSProtectionRulesServiceConfiguration.h"
#import "HEWSUnifiedMessageServiceConfiguration.h"
#import "HEWSMailTipsServiceConfiguration.h"

@implementation HEWSServiceConfigurationResponseMessageType

@synthesize mailTipsConfiguration = _mailTipsConfiguration;
@synthesize unifiedMessagingConfiguration = _unifiedMessagingConfiguration;
@synthesize protectionRulesConfiguration = _protectionRulesConfiguration;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"MailTipsConfiguration" propertyName:@"mailTipsConfiguration" type:PICO_TYPE_OBJECT clazz:[HEWSMailTipsServiceConfiguration class]];
    [map setObject:ps forKey:@"mailTipsConfiguration"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"UnifiedMessagingConfiguration" propertyName:@"unifiedMessagingConfiguration" type:PICO_TYPE_OBJECT clazz:[HEWSUnifiedMessageServiceConfiguration class]];
    [map setObject:ps forKey:@"unifiedMessagingConfiguration"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ProtectionRulesConfiguration" propertyName:@"protectionRulesConfiguration" type:PICO_TYPE_OBJECT clazz:[HEWSProtectionRulesServiceConfiguration class]];
    [map setObject:ps forKey:@"protectionRulesConfiguration"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.mailTipsConfiguration = nil;
    self.unifiedMessagingConfiguration = nil;
    self.protectionRulesConfiguration = nil;
    [super dealloc];
}

@end
