// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class HEWSDelegateUserResponseMessageType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSArrayOfDelegateUserResponseMessageType : NSObject <PicoBindable> {

@private
    NSMutableArray *_delegateUserResponseMessageType;

}


/**
 (public property)
 
 entry type : class HEWSDelegateUserResponseMessageType
*/

@property (nonatomic, retain) NSMutableArray *delegateUserResponseMessageType;


@end
