// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "HEWSBaseRequestType.h"


@class HEWSNonEmptyArrayOfUploadItemsType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSUploadItemsType : HEWSBaseRequestType {

@private
    HEWSNonEmptyArrayOfUploadItemsType *_items;

}


/**
 (public property)
 
 type : class HEWSNonEmptyArrayOfUploadItemsType
*/
@property (nonatomic, retain) HEWSNonEmptyArrayOfUploadItemsType *items;


@end
