// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "HEWSResponseMessageType.h"


@class HEWSArrayOfServiceConfigurationResponseMessageType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSGetServiceConfigurationResponseMessageType : HEWSResponseMessageType {

@private
    HEWSArrayOfServiceConfigurationResponseMessageType *_responseMessages;

}


/**
 (public property)
 
 type : class HEWSArrayOfServiceConfigurationResponseMessageType
*/
@property (nonatomic, retain) HEWSArrayOfServiceConfigurationResponseMessageType *responseMessages;


@end
