// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class HEWSArrayOfResponseMessagesType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSBaseResponseMessageType : NSObject <PicoBindable> {

@private
    HEWSArrayOfResponseMessagesType *_responseMessages;

}


/**
 (public property)
 
 type : class HEWSArrayOfResponseMessagesType
*/
@property (nonatomic, retain) HEWSArrayOfResponseMessagesType *responseMessages;


@end
