// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSGetUserAvailabilityResponseType.h"
#import "HEWSArrayOfFreeBusyResponse.h"
#import "HEWSSuggestionsResponseType.h"

@implementation HEWSGetUserAvailabilityResponseType

@synthesize freeBusyResponseArray = _freeBusyResponseArray;
@synthesize suggestionsResponse = _suggestionsResponse;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    PicoClassSchema *cs = [[PicoClassSchema alloc] initWithXmlName:@"GetUserAvailabilityResponse" nsUri:@"http://schemas.microsoft.com/exchange/services/2006/messages"];
    [cs autorelease];
    return cs;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"FreeBusyResponseArray" propertyName:@"freeBusyResponseArray" type:PICO_TYPE_OBJECT clazz:[HEWSArrayOfFreeBusyResponse class]];
    [map setObject:ps forKey:@"freeBusyResponseArray"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"SuggestionsResponse" propertyName:@"suggestionsResponse" type:PICO_TYPE_OBJECT clazz:[HEWSSuggestionsResponseType class]];
    [map setObject:ps forKey:@"suggestionsResponse"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.freeBusyResponseArray = nil;
    self.suggestionsResponse = nil;
    [super dealloc];
}

@end
