// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSUpdateItemResponseMessageType.h"
#import "HEWSConflictResultsType.h"

@implementation HEWSUpdateItemResponseMessageType

@synthesize conflictResults = _conflictResults;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    PicoClassSchema *cs = [[PicoClassSchema alloc] initWithXmlName:@"UpdateItemResponseMessage" nsUri:@"http://schemas.microsoft.com/exchange/services/2006/messages"];
    [cs autorelease];
    return cs;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ConflictResults" propertyName:@"conflictResults" type:PICO_TYPE_OBJECT clazz:[HEWSConflictResultsType class]];
    [map setObject:ps forKey:@"conflictResults"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.conflictResults = nil;
    [super dealloc];
}

@end
