// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class HEWSArrayOfFreeBusyResponse;
@class HEWSSuggestionsResponseType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSGetUserAvailabilityResponseType : NSObject <PicoBindable> {

@private
    HEWSArrayOfFreeBusyResponse *_freeBusyResponseArray;
    HEWSSuggestionsResponseType *_suggestionsResponse;

}


/**
 (public property)
 
 type : class HEWSArrayOfFreeBusyResponse
*/
@property (nonatomic, retain) HEWSArrayOfFreeBusyResponse *freeBusyResponseArray;

/**
 (public property)
 
 type : class HEWSSuggestionsResponseType
*/
@property (nonatomic, retain) HEWSSuggestionsResponseType *suggestionsResponse;


@end
