// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "HEWSResponseMessageType.h"

// abstract class

@class HEWSArrayOfDelegateUserResponseMessageType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSBaseDelegateResponseMessageType : HEWSResponseMessageType {

@private
    HEWSArrayOfDelegateUserResponseMessageType *_responseMessages;

}


/**
 (public property)
 
 type : class HEWSArrayOfDelegateUserResponseMessageType
*/
@property (nonatomic, retain) HEWSArrayOfDelegateUserResponseMessageType *responseMessages;


@end
