// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "HEWSBaseRequestType.h"


@class HEWSArrayOfTrackingPropertiesType;
@class HEWSEmailAddressType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSGetMessageTrackingReportRequestType : HEWSBaseRequestType {

@private
    NSString *_scope;
    NSString *_reportTemplate;
    HEWSEmailAddressType *_recipientFilter;
    NSString *_messageTrackingReportId;
    NSNumber *_returnQueueEvents;
    NSString *_diagnosticsLevel;
    HEWSArrayOfTrackingPropertiesType *_properties;

}


/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *scope;

/**
 (public property)
 
 type: string constant in HEWSMessageTrackingReportTemplateType.h
*/
@property (nonatomic, retain) NSString *reportTemplate;

/**
 (public property)
 
 type : class HEWSEmailAddressType
*/
@property (nonatomic, retain) HEWSEmailAddressType *recipientFilter;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *messageTrackingReportId;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *returnQueueEvents;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *diagnosticsLevel;

/**
 (public property)
 
 type : class HEWSArrayOfTrackingPropertiesType
*/
@property (nonatomic, retain) HEWSArrayOfTrackingPropertiesType *properties;


@end
