// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "HEWSBaseRequestType.h"


@class HEWSNonEmptyArrayOfApplyConversationActionType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSApplyConversationActionType : HEWSBaseRequestType {

@private
    HEWSNonEmptyArrayOfApplyConversationActionType *_conversationActions;

}


/**
 (public property)
 
 type : class HEWSNonEmptyArrayOfApplyConversationActionType
*/
@property (nonatomic, retain) HEWSNonEmptyArrayOfApplyConversationActionType *conversationActions;


@end
