// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "HEWSItemInfoResponseMessageType.h"


@class HEWSConflictResultsType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSUpdateItemResponseMessageType : HEWSItemInfoResponseMessageType {

@private
    HEWSConflictResultsType *_conflictResults;

}


/**
 (public property)
 
 type : class HEWSConflictResultsType
*/
@property (nonatomic, retain) HEWSConflictResultsType *conflictResults;


@end
