// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "HEWSBaseRequestType.h"


@class HEWSNonEmptyArrayOfAlternateIdsType;

/**
 
                 Converts the passed source ids into the destination format.  Change keys are not
                 returned.
             
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSConvertIdType : HEWSBaseRequestType {

@private
    HEWSNonEmptyArrayOfAlternateIdsType *_sourceIds;
    NSString *_destinationFormat;

}


/**
 (public property)
 
 type : class HEWSNonEmptyArrayOfAlternateIdsType
*/
@property (nonatomic, retain) HEWSNonEmptyArrayOfAlternateIdsType *sourceIds;

/**
 (public property)
 
 type: string constant in HEWSIdFormatType.h
*/
@property (nonatomic, retain) NSString *destinationFormat;


@end
