// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSGetSharingMetadataType.h"
#import "HEWSArrayOfSmtpAddressType.h"
#import "HEWSFolderIdType.h"

@implementation HEWSGetSharingMetadataType

@synthesize idOfFolderToShare = _idOfFolderToShare;
@synthesize senderSmtpAddress = _senderSmtpAddress;
@synthesize recipients = _recipients;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    PicoClassSchema *cs = [[PicoClassSchema alloc] initWithXmlName:@"GetSharingMetadata" nsUri:@"http://schemas.microsoft.com/exchange/services/2006/messages"];
    [cs autorelease];
    return cs;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"IdOfFolderToShare" propertyName:@"idOfFolderToShare" type:PICO_TYPE_OBJECT clazz:[HEWSFolderIdType class]];
    [map setObject:ps forKey:@"idOfFolderToShare"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"SenderSmtpAddress" propertyName:@"senderSmtpAddress" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"senderSmtpAddress"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Recipients" propertyName:@"recipients" type:PICO_TYPE_OBJECT clazz:[HEWSArrayOfSmtpAddressType class]];
    [map setObject:ps forKey:@"recipients"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.idOfFolderToShare = nil;
    self.senderSmtpAddress = nil;
    self.recipients = nil;
    [super dealloc];
}

@end
