// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSGetUserOofSettingsResponse.h"
#import "HEWSUserOofSettings.h"
#import "HEWSResponseMessageType.h"

@implementation HEWSGetUserOofSettingsResponse

@synthesize responseMessage = _responseMessage;
@synthesize oofSettings = _oofSettings;
@synthesize allowExternalOof = _allowExternalOof;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    PicoClassSchema *cs = [[PicoClassSchema alloc] initWithXmlName:@"GetUserOofSettingsResponse" nsUri:@"http://schemas.microsoft.com/exchange/services/2006/messages"];
    [cs autorelease];
    return cs;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ResponseMessage" propertyName:@"responseMessage" type:PICO_TYPE_OBJECT clazz:[HEWSResponseMessageType class]];
    [map setObject:ps forKey:@"responseMessage"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"OofSettings" propertyName:@"oofSettings" type:PICO_TYPE_OBJECT clazz:[HEWSUserOofSettings class]];
    [map setObject:ps forKey:@"oofSettings"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"AllowExternalOof" propertyName:@"allowExternalOof" type:PICO_TYPE_ENUM clazz:nil];
    [map setObject:ps forKey:@"allowExternalOof"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.responseMessage = nil;
    self.oofSettings = nil;
    self.allowExternalOof = nil;
    [super dealloc];
}

@end
