// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSApplyConversationActionType.h"
#import "HEWSNonEmptyArrayOfApplyConversationActionType.h"

@implementation HEWSApplyConversationActionType

@synthesize conversationActions = _conversationActions;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    PicoClassSchema *cs = [[PicoClassSchema alloc] initWithXmlName:@"ApplyConversationAction" nsUri:@"http://schemas.microsoft.com/exchange/services/2006/messages"];
    [cs autorelease];
    return cs;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ConversationActions" propertyName:@"conversationActions" type:PICO_TYPE_OBJECT clazz:[HEWSNonEmptyArrayOfApplyConversationActionType class]];
    [map setObject:ps forKey:@"conversationActions"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.conversationActions = nil;
    [super dealloc];
}

@end
