// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "HEWSResponseMessageType.h"


@class HEWSFindFolderParentType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSFindFolderResponseMessageType : HEWSResponseMessageType {

@private
    HEWSFindFolderParentType *_rootFolder;

}


/**
 (public property)
 
 type : class HEWSFindFolderParentType
*/
@property (nonatomic, retain) HEWSFindFolderParentType *rootFolder;


@end
