// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "HEWSBaseRequestType.h"


@class HEWSNonEmptyArrayOfBaseItemIdsType;
@class HEWSItemResponseShapeType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSGetItemType : HEWSBaseRequestType {

@private
    HEWSItemResponseShapeType *_itemShape;
    HEWSNonEmptyArrayOfBaseItemIdsType *_itemIds;

}


/**
 (public property)
 
 type : class HEWSItemResponseShapeType
*/
@property (nonatomic, retain) HEWSItemResponseShapeType *itemShape;

/**
 (public property)
 
 type : class HEWSNonEmptyArrayOfBaseItemIdsType
*/
@property (nonatomic, retain) HEWSNonEmptyArrayOfBaseItemIdsType *itemIds;


@end
