// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import "HEWSCalendarItemCreateOrDeleteOperationType.h"


NSString *const HEWSCalendarItemCreateOrDeleteOperationType_SEND_TO_NONE = @"SendToNone";

NSString *const HEWSCalendarItemCreateOrDeleteOperationType_SEND_ONLY_TO_ALL = @"SendOnlyToAll";

NSString *const HEWSCalendarItemCreateOrDeleteOperationType_SEND_TO_ALL_AND_SAVE_COPY = @"SendToAllAndSaveCopy";
