// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class HEWSArrayOfTransitionsType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSArrayOfTransitionsGroupsType : NSObject <PicoBindable> {

@private
    NSMutableArray *_transitionsGroup;

}


/**
 (public property)
 
 entry type : class HEWSArrayOfTransitionsType
*/

@property (nonatomic, retain) NSMutableArray *transitionsGroup;


@end
