// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class HEWSArrayOfSuggestion;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSSuggestionDayResult : NSObject <PicoBindable> {

@private
    NSDate *_date;
    NSString *_dayQuality;
    HEWSArrayOfSuggestion *_suggestionArray;

}


/**
 (public property)
 
 type : NSDate, wrapper for primitive date
*/
@property (nonatomic, retain) NSDate *date;

/**
 (public property)
 
 type: string constant in HEWSSuggestionQuality.h
*/
@property (nonatomic, retain) NSString *dayQuality;

/**
 (public property)
 
 type : class HEWSArrayOfSuggestion
*/
@property (nonatomic, retain) HEWSArrayOfSuggestion *suggestionArray;


@end
