// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSMemberType.h"
#import "HEWSEmailAddressType.h"

@implementation HEWSMemberType

@synthesize mailbox = _mailbox;
@synthesize status = _status;
@synthesize key = _key;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Mailbox" propertyName:@"mailbox" type:PICO_TYPE_OBJECT clazz:[HEWSEmailAddressType class]];
    [map setObject:ps forKey:@"mailbox"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Status" propertyName:@"status" type:PICO_TYPE_ENUM clazz:nil];
    [map setObject:ps forKey:@"status"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ATTRIBUTE xmlName:@"Key" propertyName:@"key" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"key"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.mailbox = nil;
    self.status = nil;
    self.key = nil;
    [super dealloc];
}

@end
