// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import "HEWSSharingDataType.h"


NSString *const HEWSSharingDataType_CALENDAR = @"Calendar";

NSString *const HEWSSharingDataType_CONTACTS = @"Contacts";
