// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class HEWSEndDateRecurrenceRangeType;
@class HEWSAbsoluteMonthlyRecurrencePatternType;
@class HEWSAbsoluteYearlyRecurrencePatternType;
@class HEWSNumberedRecurrenceRangeType;
@class HEWSWeeklyRecurrencePatternType;
@class HEWSRelativeMonthlyRecurrencePatternType;
@class HEWSRelativeYearlyRecurrencePatternType;
@class HEWSNoEndRecurrenceRangeType;
@class HEWSDailyRecurrencePatternType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSRecurrenceType : NSObject <PicoBindable> {

@private
    HEWSRelativeYearlyRecurrencePatternType *_relativeYearlyRecurrence;
    HEWSAbsoluteYearlyRecurrencePatternType *_absoluteYearlyRecurrence;
    HEWSRelativeMonthlyRecurrencePatternType *_relativeMonthlyRecurrence;
    HEWSAbsoluteMonthlyRecurrencePatternType *_absoluteMonthlyRecurrence;
    HEWSWeeklyRecurrencePatternType *_weeklyRecurrence;
    HEWSDailyRecurrencePatternType *_dailyRecurrence;
    HEWSNoEndRecurrenceRangeType *_noEndRecurrence;
    HEWSEndDateRecurrenceRangeType *_endDateRecurrence;
    HEWSNumberedRecurrenceRangeType *_numberedRecurrence;

}


/**
 (public property)
 
 type : class HEWSRelativeYearlyRecurrencePatternType
*/
@property (nonatomic, retain) HEWSRelativeYearlyRecurrencePatternType *relativeYearlyRecurrence;

/**
 (public property)
 
 type : class HEWSAbsoluteYearlyRecurrencePatternType
*/
@property (nonatomic, retain) HEWSAbsoluteYearlyRecurrencePatternType *absoluteYearlyRecurrence;

/**
 (public property)
 
 type : class HEWSRelativeMonthlyRecurrencePatternType
*/
@property (nonatomic, retain) HEWSRelativeMonthlyRecurrencePatternType *relativeMonthlyRecurrence;

/**
 (public property)
 
 type : class HEWSAbsoluteMonthlyRecurrencePatternType
*/
@property (nonatomic, retain) HEWSAbsoluteMonthlyRecurrencePatternType *absoluteMonthlyRecurrence;

/**
 (public property)
 
 type : class HEWSWeeklyRecurrencePatternType
*/
@property (nonatomic, retain) HEWSWeeklyRecurrencePatternType *weeklyRecurrence;

/**
 (public property)
 
 type : class HEWSDailyRecurrencePatternType
*/
@property (nonatomic, retain) HEWSDailyRecurrencePatternType *dailyRecurrence;

/**
 (public property)
 
 type : class HEWSNoEndRecurrenceRangeType
*/
@property (nonatomic, retain) HEWSNoEndRecurrenceRangeType *noEndRecurrence;

/**
 (public property)
 
 type : class HEWSEndDateRecurrenceRangeType
*/
@property (nonatomic, retain) HEWSEndDateRecurrenceRangeType *endDateRecurrence;

/**
 (public property)
 
 type : class HEWSNumberedRecurrenceRangeType
*/
@property (nonatomic, retain) HEWSNumberedRecurrenceRangeType *numberedRecurrence;


@end
