// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>


extern NSString *const HEWSDeliverMeetingRequestsType_DELEGATES_ONLY;

extern NSString *const HEWSDeliverMeetingRequestsType_DELEGATES_AND_ME;

extern NSString *const HEWSDeliverMeetingRequestsType_DELEGATES_AND_SEND_INFORMATION_TO_ME;

extern NSString *const HEWSDeliverMeetingRequestsType_NO_FORWARD;
