// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "HEWSBaseFolderType.h"


@class HEWSCalendarPermissionSetType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSCalendarFolderType : HEWSBaseFolderType {

@private
    NSString *_sharingEffectiveRights;
    HEWSCalendarPermissionSetType *_permissionSet;

}


/**
 (public property)
 
 type: string constant in HEWSCalendarPermissionReadAccessType.h
*/
@property (nonatomic, retain) NSString *sharingEffectiveRights;

/**
 (public property)
 
 type : class HEWSCalendarPermissionSetType
*/
@property (nonatomic, retain) HEWSCalendarPermissionSetType *permissionSet;


@end
