// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "HEWSBasePathToElementType.h"



/**
 
         Represents an extended property.  Note that there are only a couple of valid attribute
         combinations.  Note that all occurances require the PropertyType attribute.
 
         1.  (DistinguishedPropertySetId || PropertySetId) + (PropertyName || Property Id)
         2.  PropertyTag
 
       
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSPathToExtendedFieldType : HEWSBasePathToElementType {

@private
    NSString *_distinguishedPropertySetId;
    NSString *_propertySetId;
    NSString *_propertyTag;
    NSString *_propertyName;
    NSNumber *_propertyId;
    NSString *_propertyType;

}


/**
 (public property)
 
 type: string constant in HEWSDistinguishedPropertySetType.h
*/
@property (nonatomic, retain) NSString *distinguishedPropertySetId;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *propertySetId;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *propertyTag;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *propertyName;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *propertyId;

/**
 (public property)
 
 type: string constant in HEWSMapiPropertyTypeType.h
*/
@property (nonatomic, retain) NSString *propertyType;


@end
