// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>


extern NSString *const HEWSCompleteActionType_COMMIT;

extern NSString *const HEWSCompleteActionType_ABANDON;
