// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import "HEWSRuleFieldURIType.h"

/**
 @file
 Rule field URI enumerates all possible rule fields that could trigger validation error
*/

NSString *const HEWSRuleFieldURIType_RULE_ID = @"RuleId";

NSString *const HEWSRuleFieldURIType_DISPLAY_NAME = @"DisplayName";

NSString *const HEWSRuleFieldURIType_PRIORITY = @"Priority";

NSString *const HEWSRuleFieldURIType_IS_NOT_SUPPORTED = @"IsNotSupported";

NSString *const HEWSRuleFieldURIType_ACTIONS = @"Actions";

NSString *const HEWSRuleFieldURIType_CONDITION_CATEGORIES = @"Condition:Categories";

NSString *const HEWSRuleFieldURIType_CONDITION_CONTAINS_BODY_STRINGS = @"Condition:ContainsBodyStrings";

NSString *const HEWSRuleFieldURIType_CONDITION_CONTAINS_HEADER_STRINGS = @"Condition:ContainsHeaderStrings";

NSString *const HEWSRuleFieldURIType_CONDITION_CONTAINS_RECIPIENT_STRINGS = @"Condition:ContainsRecipientStrings";

NSString *const HEWSRuleFieldURIType_CONDITION_CONTAINS_SENDER_STRINGS = @"Condition:ContainsSenderStrings";

NSString *const HEWSRuleFieldURIType_CONDITION_CONTAINS_SUBJECT_OR_BODY_STRINGS = @"Condition:ContainsSubjectOrBodyStrings";

NSString *const HEWSRuleFieldURIType_CONDITION_CONTAINS_SUBJECT_STRINGS = @"Condition:ContainsSubjectStrings";

NSString *const HEWSRuleFieldURIType_CONDITION_FLAGGED_FOR_ACTION = @"Condition:FlaggedForAction";

NSString *const HEWSRuleFieldURIType_CONDITION_FROM_ADDRESSES = @"Condition:FromAddresses";

NSString *const HEWSRuleFieldURIType_CONDITION_FROM_CONNECTED_ACCOUNTS = @"Condition:FromConnectedAccounts";

NSString *const HEWSRuleFieldURIType_CONDITION_HAS_ATTACHMENTS = @"Condition:HasAttachments";

NSString *const HEWSRuleFieldURIType_CONDITION_IMPORTANCE = @"Condition:Importance";

NSString *const HEWSRuleFieldURIType_CONDITION_IS_APPROVAL_REQUEST = @"Condition:IsApprovalRequest";

NSString *const HEWSRuleFieldURIType_CONDITION_IS_AUTOMATIC_FORWARD = @"Condition:IsAutomaticForward";

NSString *const HEWSRuleFieldURIType_CONDITION_IS_AUTOMATIC_REPLY = @"Condition:IsAutomaticReply";

NSString *const HEWSRuleFieldURIType_CONDITION_IS_ENCRYPTED = @"Condition:IsEncrypted";

NSString *const HEWSRuleFieldURIType_CONDITION_IS_MEETING_REQUEST = @"Condition:IsMeetingRequest";

NSString *const HEWSRuleFieldURIType_CONDITION_IS_MEETING_RESPONSE = @"Condition:IsMeetingResponse";

NSString *const HEWSRuleFieldURIType_CONDITION_IS_NDR = @"Condition:IsNDR";

NSString *const HEWSRuleFieldURIType_CONDITION_IS_PERMISSION_CONTROLLED = @"Condition:IsPermissionControlled";

NSString *const HEWSRuleFieldURIType_CONDITION_IS_READ_RECEIPT = @"Condition:IsReadReceipt";

NSString *const HEWSRuleFieldURIType_CONDITION_IS_SIGNED = @"Condition:IsSigned";

NSString *const HEWSRuleFieldURIType_CONDITION_IS_VOICEMAIL = @"Condition:IsVoicemail";

NSString *const HEWSRuleFieldURIType_CONDITION_ITEM_CLASSES = @"Condition:ItemClasses";

NSString *const HEWSRuleFieldURIType_CONDITION_MESSAGE_CLASSIFICATIONS = @"Condition:MessageClassifications";

NSString *const HEWSRuleFieldURIType_CONDITION_NOT_SENT_TO_ME = @"Condition:NotSentToMe";

NSString *const HEWSRuleFieldURIType_CONDITION_SENT_CC_ME = @"Condition:SentCcMe";

NSString *const HEWSRuleFieldURIType_CONDITION_SENT_ONLY_TO_ME = @"Condition:SentOnlyToMe";

NSString *const HEWSRuleFieldURIType_CONDITION_SENT_TO_ADDRESSES = @"Condition:SentToAddresses";

NSString *const HEWSRuleFieldURIType_CONDITION_SENT_TO_ME = @"Condition:SentToMe";

NSString *const HEWSRuleFieldURIType_CONDITION_SENT_TO_OR_CC_ME = @"Condition:SentToOrCcMe";

NSString *const HEWSRuleFieldURIType_CONDITION_SENSITIVITY = @"Condition:Sensitivity";

NSString *const HEWSRuleFieldURIType_CONDITION_WITHIN_DATE_RANGE = @"Condition:WithinDateRange";

NSString *const HEWSRuleFieldURIType_CONDITION_WITHIN_SIZE_RANGE = @"Condition:WithinSizeRange";

NSString *const HEWSRuleFieldURIType_EXCEPTION_CATEGORIES = @"Exception:Categories";

NSString *const HEWSRuleFieldURIType_EXCEPTION_CONTAINS_BODY_STRINGS = @"Exception:ContainsBodyStrings";

NSString *const HEWSRuleFieldURIType_EXCEPTION_CONTAINS_HEADER_STRINGS = @"Exception:ContainsHeaderStrings";

NSString *const HEWSRuleFieldURIType_EXCEPTION_CONTAINS_RECIPIENT_STRINGS = @"Exception:ContainsRecipientStrings";

NSString *const HEWSRuleFieldURIType_EXCEPTION_CONTAINS_SENDER_STRINGS = @"Exception:ContainsSenderStrings";

NSString *const HEWSRuleFieldURIType_EXCEPTION_CONTAINS_SUBJECT_OR_BODY_STRINGS = @"Exception:ContainsSubjectOrBodyStrings";

NSString *const HEWSRuleFieldURIType_EXCEPTION_CONTAINS_SUBJECT_STRINGS = @"Exception:ContainsSubjectStrings";

NSString *const HEWSRuleFieldURIType_EXCEPTION_FLAGGED_FOR_ACTION = @"Exception:FlaggedForAction";

NSString *const HEWSRuleFieldURIType_EXCEPTION_FROM_ADDRESSES = @"Exception:FromAddresses";

NSString *const HEWSRuleFieldURIType_EXCEPTION_FROM_CONNECTED_ACCOUNTS = @"Exception:FromConnectedAccounts";

NSString *const HEWSRuleFieldURIType_EXCEPTION_HAS_ATTACHMENTS = @"Exception:HasAttachments";

NSString *const HEWSRuleFieldURIType_EXCEPTION_IMPORTANCE = @"Exception:Importance";

NSString *const HEWSRuleFieldURIType_EXCEPTION_IS_APPROVAL_REQUEST = @"Exception:IsApprovalRequest";

NSString *const HEWSRuleFieldURIType_EXCEPTION_IS_AUTOMATIC_FORWARD = @"Exception:IsAutomaticForward";

NSString *const HEWSRuleFieldURIType_EXCEPTION_IS_AUTOMATIC_REPLY = @"Exception:IsAutomaticReply";

NSString *const HEWSRuleFieldURIType_EXCEPTION_IS_ENCRYPTED = @"Exception:IsEncrypted";

NSString *const HEWSRuleFieldURIType_EXCEPTION_IS_MEETING_REQUEST = @"Exception:IsMeetingRequest";

NSString *const HEWSRuleFieldURIType_EXCEPTION_IS_MEETING_RESPONSE = @"Exception:IsMeetingResponse";

NSString *const HEWSRuleFieldURIType_EXCEPTION_IS_NDR = @"Exception:IsNDR";

NSString *const HEWSRuleFieldURIType_EXCEPTION_IS_PERMISSION_CONTROLLED = @"Exception:IsPermissionControlled";

NSString *const HEWSRuleFieldURIType_EXCEPTION_IS_READ_RECEIPT = @"Exception:IsReadReceipt";

NSString *const HEWSRuleFieldURIType_EXCEPTION_IS_SIGNED = @"Exception:IsSigned";

NSString *const HEWSRuleFieldURIType_EXCEPTION_IS_VOICEMAIL = @"Exception:IsVoicemail";

NSString *const HEWSRuleFieldURIType_EXCEPTION_ITEM_CLASSES = @"Exception:ItemClasses";

NSString *const HEWSRuleFieldURIType_EXCEPTION_MESSAGE_CLASSIFICATIONS = @"Exception:MessageClassifications";

NSString *const HEWSRuleFieldURIType_EXCEPTION_NOT_SENT_TO_ME = @"Exception:NotSentToMe";

NSString *const HEWSRuleFieldURIType_EXCEPTION_SENT_CC_ME = @"Exception:SentCcMe";

NSString *const HEWSRuleFieldURIType_EXCEPTION_SENT_ONLY_TO_ME = @"Exception:SentOnlyToMe";

NSString *const HEWSRuleFieldURIType_EXCEPTION_SENT_TO_ADDRESSES = @"Exception:SentToAddresses";

NSString *const HEWSRuleFieldURIType_EXCEPTION_SENT_TO_ME = @"Exception:SentToMe";

NSString *const HEWSRuleFieldURIType_EXCEPTION_SENT_TO_OR_CC_ME = @"Exception:SentToOrCcMe";

NSString *const HEWSRuleFieldURIType_EXCEPTION_SENSITIVITY = @"Exception:Sensitivity";

NSString *const HEWSRuleFieldURIType_EXCEPTION_WITHIN_DATE_RANGE = @"Exception:WithinDateRange";

NSString *const HEWSRuleFieldURIType_EXCEPTION_WITHIN_SIZE_RANGE = @"Exception:WithinSizeRange";

NSString *const HEWSRuleFieldURIType_ACTION_ASSIGN_CATEGORIES = @"Action:AssignCategories";

NSString *const HEWSRuleFieldURIType_ACTION_COPY_TO_FOLDER = @"Action:CopyToFolder";

NSString *const HEWSRuleFieldURIType_ACTION_DELETE = @"Action:Delete";

NSString *const HEWSRuleFieldURIType_ACTION_FORWARD_AS_ATTACHMENT_TO_RECIPIENTS = @"Action:ForwardAsAttachmentToRecipients";

NSString *const HEWSRuleFieldURIType_ACTION_FORWARD_TO_RECIPIENTS = @"Action:ForwardToRecipients";

NSString *const HEWSRuleFieldURIType_ACTION_MARK_IMPORTANCE = @"Action:MarkImportance";

NSString *const HEWSRuleFieldURIType_ACTION_MARK_AS_READ = @"Action:MarkAsRead";

NSString *const HEWSRuleFieldURIType_ACTION_MOVE_TO_FOLDER = @"Action:MoveToFolder";

NSString *const HEWSRuleFieldURIType_ACTION_PERMANENT_DELETE = @"Action:PermanentDelete";

NSString *const HEWSRuleFieldURIType_ACTION_REDIRECT_TO_RECIPIENTS = @"Action:RedirectToRecipients";

NSString *const HEWSRuleFieldURIType_ACTION_SEND_SMS_ALERT_TO_RECIPIENTS = @"Action:SendSMSAlertToRecipients";

NSString *const HEWSRuleFieldURIType_ACTION_SERVER_REPLY_WITH_MESSAGE = @"Action:ServerReplyWithMessage";

NSString *const HEWSRuleFieldURIType_ACTION_STOP_PROCESSING_RULES = @"Action:StopProcessingRules";

NSString *const HEWSRuleFieldURIType_IS_ENABLED = @"IsEnabled";

NSString *const HEWSRuleFieldURIType_IS_IN_ERROR = @"IsInError";

NSString *const HEWSRuleFieldURIType_CONDITIONS = @"Conditions";

NSString *const HEWSRuleFieldURIType_EXCEPTIONS = @"Exceptions";
