// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "HEWSBaseSubscriptionRequestType.h"



/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSPushSubscriptionRequestType : HEWSBaseSubscriptionRequestType {

@private
    NSNumber *_statusFrequency;
    NSString *_url;

}


/**
 (public property)
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *statusFrequency;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *url;


@end
