// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"

// abstract class


/**
 Represents a rule operation to be performed
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSRuleOperationType : NSObject <PicoBindable> {

@private

}



@end
