// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class HEWSImAddressDictionaryEntryType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSImAddressDictionaryType : NSObject <PicoBindable> {

@private
    NSMutableArray *_entry;

}


/**
 (public property)
 
 entry type : class HEWSImAddressDictionaryEntryType
*/

@property (nonatomic, retain) NSMutableArray *entry;


@end
