// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class HEWSItemIdType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSNonEmptyArrayOfItemIdsType : NSObject <PicoBindable> {

@private
    NSMutableArray *_itemId;

}


/**
 (public property)
 
 entry type : class HEWSItemIdType
*/

@property (nonatomic, retain) NSMutableArray *itemId;


@end
