// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>


extern NSString *const HEWSDisposalType_HARD_DELETE;

extern NSString *const HEWSDisposalType_SOFT_DELETE;

extern NSString *const HEWSDisposalType_MOVE_TO_DELETED_ITEMS;
