// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "HEWSBasePermissionType.h"



/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSCalendarPermissionType : HEWSBasePermissionType {

@private
    NSString *_readItems;
    NSString *_calendarPermissionLevel;

}


/**
 (public property)
 
 type: string constant in HEWSCalendarPermissionReadAccessType.h
*/
@property (nonatomic, retain) NSString *readItems;

/**
 (public property)
 
 type: string constant in HEWSCalendarPermissionLevelType.h
*/
@property (nonatomic, retain) NSString *calendarPermissionLevel;


@end
