// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class HEWSAlternateIdBaseType;

/**
 
         A non-empty array of alternate Ids.
       
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSNonEmptyArrayOfAlternateIdsType : NSObject <PicoBindable> {

@private
    NSMutableArray *_alternateIdOrAlternatePublicFolderIdOrAlternatePublicFolderItemId;

}


/**
 (public property)
 
 entry type : class HEWSAlternateIdBaseType
*/

@property (nonatomic, retain) NSMutableArray *alternateIdOrAlternatePublicFolderIdOrAlternatePublicFolderItemId;


@end
