// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSImAddressDictionaryType.h"
#import "HEWSImAddressDictionaryEntryType.h"

@implementation HEWSImAddressDictionaryType

@synthesize entry = _entry;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"Entry" propertyName:@"entry" type:PICO_TYPE_OBJECT clazz:[HEWSImAddressDictionaryEntryType class]];
    [map setObject:ps forKey:@"entry"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.entry = nil;
    [super dealloc];
}

@end
