// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "HEWSRecurrenceRangeBaseType.h"



/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSNumberedRecurrenceRangeType : HEWSRecurrenceRangeBaseType {

@private
    NSNumber *_numberOfOccurrences;

}


/**
 (public property)
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *numberOfOccurrences;


@end
