// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSProtectionRulesServiceConfiguration.h"
#import "HEWSArrayOfProtectionRulesType.h"
#import "HEWSSmtpDomainList.h"

@implementation HEWSProtectionRulesServiceConfiguration

@synthesize rules = _rules;
@synthesize internalDomains = _internalDomains;
@synthesize refreshInterval = _refreshInterval;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Rules" propertyName:@"rules" type:PICO_TYPE_OBJECT clazz:[HEWSArrayOfProtectionRulesType class]];
    [map setObject:ps forKey:@"rules"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"InternalDomains" propertyName:@"internalDomains" type:PICO_TYPE_OBJECT clazz:[HEWSSmtpDomainList class]];
    [map setObject:ps forKey:@"internalDomains"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ATTRIBUTE xmlName:@"RefreshInterval" propertyName:@"refreshInterval" type:PICO_TYPE_INT clazz:nil];
    [map setObject:ps forKey:@"refreshInterval"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.rules = nil;
    self.internalDomains = nil;
    self.refreshInterval = nil;
    [super dealloc];
}

@end
