// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class HEWSSuggestionDayResult;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSArrayOfSuggestionDayResult : NSObject <PicoBindable> {

@private
    NSMutableArray *_suggestionDayResult;

}


/**
 (public property)
 
 entry type : class HEWSSuggestionDayResult
*/

@property (nonatomic, retain) NSMutableArray *suggestionDayResult;


@end
