// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "HEWSAttachmentType.h"


@class HEWSMeetingRequestMessageType;
@class HEWSTaskType;
@class HEWSMeetingResponseMessageType;
@class HEWSContactItemType;
@class HEWSMeetingCancellationMessageType;
@class HEWSPostItemType;
@class HEWSCalendarItemType;
@class HEWSMessageType;
@class HEWSMeetingMessageType;
@class HEWSItemType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSItemAttachmentType : HEWSAttachmentType {

@private
    HEWSItemType *_item;
    HEWSMessageType *_message;
    HEWSCalendarItemType *_calendarItem;
    HEWSContactItemType *_contact;
    HEWSMeetingMessageType *_meetingMessage;
    HEWSMeetingRequestMessageType *_meetingRequest;
    HEWSMeetingResponseMessageType *_meetingResponse;
    HEWSMeetingCancellationMessageType *_meetingCancellation;
    HEWSTaskType *_task;
    HEWSPostItemType *_postItem;

}


/**
 (public property)
 
 type : class HEWSItemType
*/
@property (nonatomic, retain) HEWSItemType *item;

/**
 (public property)
 
 type : class HEWSMessageType
*/
@property (nonatomic, retain) HEWSMessageType *message;

/**
 (public property)
 
 type : class HEWSCalendarItemType
*/
@property (nonatomic, retain) HEWSCalendarItemType *calendarItem;

/**
 (public property)
 
 type : class HEWSContactItemType
*/
@property (nonatomic, retain) HEWSContactItemType *contact;

/**
 (public property)
 
 type : class HEWSMeetingMessageType
*/
@property (nonatomic, retain) HEWSMeetingMessageType *meetingMessage;

/**
 (public property)
 
 type : class HEWSMeetingRequestMessageType
*/
@property (nonatomic, retain) HEWSMeetingRequestMessageType *meetingRequest;

/**
 (public property)
 
 type : class HEWSMeetingResponseMessageType
*/
@property (nonatomic, retain) HEWSMeetingResponseMessageType *meetingResponse;

/**
 (public property)
 
 type : class HEWSMeetingCancellationMessageType
*/
@property (nonatomic, retain) HEWSMeetingCancellationMessageType *meetingCancellation;

/**
 (public property)
 
 type : class HEWSTaskType
*/
@property (nonatomic, retain) HEWSTaskType *task;

/**
 (public property)
 
 type : class HEWSPostItemType
*/
@property (nonatomic, retain) HEWSPostItemType *postItem;


@end
