// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSConnectingSIDType.h"

@implementation HEWSConnectingSIDType

@synthesize principalName = _principalName;
@synthesize sid = _sid;
@synthesize primarySmtpAddress = _primarySmtpAddress;
@synthesize smtpAddress = _smtpAddress;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"PrincipalName" propertyName:@"principalName" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"principalName"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"SID" propertyName:@"sid" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"sid"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"PrimarySmtpAddress" propertyName:@"primarySmtpAddress" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"primarySmtpAddress"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"SmtpAddress" propertyName:@"smtpAddress" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"smtpAddress"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.principalName = nil;
    self.sid = nil;
    self.primarySmtpAddress = nil;
    self.smtpAddress = nil;
    [super dealloc];
}

@end
