// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import "HEWSMailboxTypeType.h"


NSString *const HEWSMailboxTypeType_UNKNOWN = @"Unknown";

NSString *const HEWSMailboxTypeType_ONE_OFF = @"OneOff";

NSString *const HEWSMailboxTypeType_MAILBOX = @"Mailbox";

NSString *const HEWSMailboxTypeType_PUBLIC_DL = @"PublicDL";

NSString *const HEWSMailboxTypeType_PRIVATE_DL = @"PrivateDL";

NSString *const HEWSMailboxTypeType_CONTACT = @"Contact";

NSString *const HEWSMailboxTypeType_PUBLIC_FOLDER = @"PublicFolder";
