// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class HEWSArrayOfFoldersType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSFindFolderParentType : NSObject <PicoBindable> {

@private
    HEWSArrayOfFoldersType *_folders;
    NSNumber *_indexedPagingOffset;
    NSNumber *_numeratorOffset;
    NSNumber *_absoluteDenominator;
    NSNumber *_includesLastItemInRange;
    NSNumber *_totalItemsInView;

}


/**
 (public property)
 
 type : class HEWSArrayOfFoldersType
*/
@property (nonatomic, retain) HEWSArrayOfFoldersType *folders;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *indexedPagingOffset;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *numeratorOffset;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *absoluteDenominator;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *includesLastItemInRange;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *totalItemsInView;


@end
