// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>


extern NSString *const HEWSOofState_DISABLED;

extern NSString *const HEWSOofState_ENABLED;

extern NSString *const HEWSOofState_SCHEDULED;
