// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class HEWSRoomType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSArrayOfRoomsType : NSObject <PicoBindable> {

@private
    NSMutableArray *_room;

}


/**
 (public property)
 
 entry type : class HEWSRoomType
*/

@property (nonatomic, retain) NSMutableArray *room;


@end
