// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class HEWSDelegatePermissionsType;
@class HEWSUserIdType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSDelegateUserType : NSObject <PicoBindable> {

@private
    HEWSUserIdType *_userId;
    HEWSDelegatePermissionsType *_delegatePermissions;
    NSNumber *_receiveCopiesOfMeetingMessages;
    NSNumber *_viewPrivateItems;

}


/**
 (public property)
 
 type : class HEWSUserIdType
*/
@property (nonatomic, retain) HEWSUserIdType *userId;

/**
 (public property)
 
 type : class HEWSDelegatePermissionsType
*/
@property (nonatomic, retain) HEWSDelegatePermissionsType *delegatePermissions;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *receiveCopiesOfMeetingMessages;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *viewPrivateItems;


@end
