// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSUserOofSettings.h"
#import "HEWSReplyBody.h"
#import "HEWSDuration.h"

@implementation HEWSUserOofSettings

@synthesize oofState = _oofState;
@synthesize externalAudience = _externalAudience;
@synthesize duration = _duration;
@synthesize internalReply = _internalReply;
@synthesize externalReply = _externalReply;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    PicoClassSchema *cs = [[PicoClassSchema alloc] initWithXmlName:@"UserOofSettings" nsUri:@"http://schemas.microsoft.com/exchange/services/2006/types"];
    [cs autorelease];
    return cs;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"OofState" propertyName:@"oofState" type:PICO_TYPE_ENUM clazz:nil];
    [map setObject:ps forKey:@"oofState"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ExternalAudience" propertyName:@"externalAudience" type:PICO_TYPE_ENUM clazz:nil];
    [map setObject:ps forKey:@"externalAudience"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Duration" propertyName:@"duration" type:PICO_TYPE_OBJECT clazz:[HEWSDuration class]];
    [map setObject:ps forKey:@"duration"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"InternalReply" propertyName:@"internalReply" type:PICO_TYPE_OBJECT clazz:[HEWSReplyBody class]];
    [map setObject:ps forKey:@"internalReply"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ExternalReply" propertyName:@"externalReply" type:PICO_TYPE_OBJECT clazz:[HEWSReplyBody class]];
    [map setObject:ps forKey:@"externalReply"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.oofState = nil;
    self.externalAudience = nil;
    self.duration = nil;
    self.internalReply = nil;
    self.externalReply = nil;
    [super dealloc];
}

@end
