// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "HEWSSearchExpressionType.h"

// abstract class

@class HEWSJAXBElement<? extends BasePathToElementType>;
@class HEWSFieldURIOrConstantType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSTwoOperandExpressionType : HEWSSearchExpressionType {

@private
    NSMutableArray *_path;
    HEWSFieldURIOrConstantType *_fieldURIOrConstant;

}


/**
 (public property)
 
 entry type : HEWSJAXBElement<? extends BasePathToElementType>, wrapper for primitive object
*/
@property (nonatomic, retain) NSMutableArray *path;

/**
 (public property)
 
 type : class HEWSFieldURIOrConstantType
*/
@property (nonatomic, retain) HEWSFieldURIOrConstantType *fieldURIOrConstant;


@end
