// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSRuleValidationErrorType.h"

@implementation HEWSRuleValidationErrorType

@synthesize fieldURI = _fieldURI;
@synthesize errorCode = _errorCode;
@synthesize errorMessage = _errorMessage;
@synthesize fieldValue = _fieldValue;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"FieldURI" propertyName:@"fieldURI" type:PICO_TYPE_ENUM clazz:nil];
    [map setObject:ps forKey:@"fieldURI"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ErrorCode" propertyName:@"errorCode" type:PICO_TYPE_ENUM clazz:nil];
    [map setObject:ps forKey:@"errorCode"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ErrorMessage" propertyName:@"errorMessage" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"errorMessage"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"FieldValue" propertyName:@"fieldValue" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"fieldValue"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.fieldURI = nil;
    self.errorCode = nil;
    self.errorMessage = nil;
    self.fieldValue = nil;
    [super dealloc];
}

@end
