// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>


extern NSString *const HEWSResolveNamesSearchScopeType_ACTIVE_DIRECTORY;

extern NSString *const HEWSResolveNamesSearchScopeType_ACTIVE_DIRECTORY_CONTACTS;

extern NSString *const HEWSResolveNamesSearchScopeType_CONTACTS;

extern NSString *const HEWSResolveNamesSearchScopeType_CONTACTS_ACTIVE_DIRECTORY;
