// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class HEWSJAXBElement<? extends SearchExpressionType>;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSRestrictionType : NSObject <PicoBindable> {

@private
    NSMutableArray *_searchExpression;

}


/**
 (public property)
 
 entry type : HEWSJAXBElement<? extends SearchExpressionType>, wrapper for primitive object
*/
@property (nonatomic, retain) NSMutableArray *searchExpression;


@end
