// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "HEWSServiceConfiguration.h"


@class HEWSSmtpDomainList;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSMailTipsServiceConfiguration : HEWSServiceConfiguration {

@private
    NSNumber *_mailTipsEnabled;
    NSNumber *_maxRecipientsPerGetMailTipsRequest;
    NSNumber *_maxMessageSize;
    NSNumber *_largeAudienceThreshold;
    NSNumber *_showExternalRecipientCount;
    HEWSSmtpDomainList *_internalDomains;

}


/**
 (public property)
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *mailTipsEnabled;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *maxRecipientsPerGetMailTipsRequest;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *maxMessageSize;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *largeAudienceThreshold;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *showExternalRecipientCount;

/**
 (public property)
 
 type : class HEWSSmtpDomainList
*/
@property (nonatomic, retain) HEWSSmtpDomainList *internalDomains;


@end
