// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class HEWSSidAndAttributesType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSNonEmptyArrayOfRestrictedGroupIdentifiersType : NSObject <PicoBindable> {

@private
    NSMutableArray *_restrictedGroupIdentifier;

}


/**
 (public property)
 
 entry type : class HEWSSidAndAttributesType
*/

@property (nonatomic, retain) NSMutableArray *restrictedGroupIdentifier;


@end
