// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"



/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSPhoneCallInformationType : NSObject <PicoBindable> {

@private
    NSString *_phoneCallState;
    NSString *_connectionFailureCause;
    NSString *_sipResponseText;
    NSNumber *_sipResponseCode;

}


/**
 (public property)
 
 type: string constant in HEWSPhoneCallStateType.h
*/
@property (nonatomic, retain) NSString *phoneCallState;

/**
 (public property)
 
 type: string constant in HEWSConnectionFailureCauseType.h
*/
@property (nonatomic, retain) NSString *connectionFailureCause;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *sipResponseText;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *sipResponseCode;


@end
