// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class HEWSArrayOfTrackingPropertiesType;
@class HEWSArrayOfEmailAddressesType;
@class HEWSEmailAddressType;
@class HEWSArrayOfRecipientTrackingEventType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSMessageTrackingReportType : NSObject <PicoBindable> {

@private
    HEWSEmailAddressType *_sender;
    HEWSEmailAddressType *_purportedSender;
    NSString *_subject;
    NSDate *_submitTime;
    HEWSArrayOfEmailAddressesType *_originalRecipients;
    HEWSArrayOfRecipientTrackingEventType *_recipientTrackingEvents;
    HEWSArrayOfTrackingPropertiesType *_properties;

}


/**
 (public property)
 
 type : class HEWSEmailAddressType
*/
@property (nonatomic, retain) HEWSEmailAddressType *sender;

/**
 (public property)
 
 type : class HEWSEmailAddressType
*/
@property (nonatomic, retain) HEWSEmailAddressType *purportedSender;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *subject;

/**
 (public property)
 
 type : NSDate, wrapper for primitive date
*/
@property (nonatomic, retain) NSDate *submitTime;

/**
 (public property)
 
 type : class HEWSArrayOfEmailAddressesType
*/
@property (nonatomic, retain) HEWSArrayOfEmailAddressesType *originalRecipients;

/**
 (public property)
 
 type : class HEWSArrayOfRecipientTrackingEventType
*/
@property (nonatomic, retain) HEWSArrayOfRecipientTrackingEventType *recipientTrackingEvents;

/**
 (public property)
 
 type : class HEWSArrayOfTrackingPropertiesType
*/
@property (nonatomic, retain) HEWSArrayOfTrackingPropertiesType *properties;


@end
