// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"



/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSUserIdType : NSObject <PicoBindable> {

@private
    NSString *_sid;
    NSString *_primarySmtpAddress;
    NSString *_displayName;
    NSString *_distinguishedUser;
    NSString *_externalUserIdentity;

}


/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *sid;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *primarySmtpAddress;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *displayName;

/**
 (public property)
 
 type: string constant in HEWSDistinguishedUserType.h
*/
@property (nonatomic, retain) NSString *distinguishedUser;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *externalUserIdentity;


@end
