// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import "HEWSMonthNamesType.h"


NSString *const HEWSMonthNamesType_JANUARY = @"January";

NSString *const HEWSMonthNamesType_FEBRUARY = @"February";

NSString *const HEWSMonthNamesType_MARCH = @"March";

NSString *const HEWSMonthNamesType_APRIL = @"April";

NSString *const HEWSMonthNamesType_MAY = @"May";

NSString *const HEWSMonthNamesType_JUNE = @"June";

NSString *const HEWSMonthNamesType_JULY = @"July";

NSString *const HEWSMonthNamesType_AUGUST = @"August";

NSString *const HEWSMonthNamesType_SEPTEMBER = @"September";

NSString *const HEWSMonthNamesType_OCTOBER = @"October";

NSString *const HEWSMonthNamesType_NOVEMBER = @"November";

NSString *const HEWSMonthNamesType_DECEMBER = @"December";
