// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSNonEmptyArrayOfBaseFolderIdsType.h"
#import "HEWSBaseFolderIdType.h"

@implementation HEWSNonEmptyArrayOfBaseFolderIdsType

@synthesize folderIdOrDistinguishedFolderId = _folderIdOrDistinguishedFolderId;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"folderIdOrDistinguishedFolderId" propertyName:@"folderIdOrDistinguishedFolderId" type:PICO_TYPE_OBJECT clazz:[HEWSBaseFolderIdType class]];
    [map setObject:ps forKey:@"folderIdOrDistinguishedFolderId"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.folderIdOrDistinguishedFolderId = nil;
    [super dealloc];
}

@end
