// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSArrayOfTimeZoneDefinitionType.h"
#import "HEWSTimeZoneDefinitionType.h"

@implementation HEWSArrayOfTimeZoneDefinitionType

@synthesize timeZoneDefinition = _timeZoneDefinition;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"TimeZoneDefinition" propertyName:@"timeZoneDefinition" type:PICO_TYPE_OBJECT clazz:[HEWSTimeZoneDefinitionType class]];
    [map setObject:ps forKey:@"timeZoneDefinition"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.timeZoneDefinition = nil;
    [super dealloc];
}

@end
