// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "HEWSDirectoryEntryType.h"



/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSRoomType : HEWSDirectoryEntryType {

@private

}



@end
