// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>


extern NSString *const HEWSTaskDelegateStateType_NO_MATCH;

extern NSString *const HEWSTaskDelegateStateType_OWN_NEW;

extern NSString *const HEWSTaskDelegateStateType_OWNED;

extern NSString *const HEWSTaskDelegateStateType_ACCEPTED;

extern NSString *const HEWSTaskDelegateStateType_DECLINED;

extern NSString *const HEWSTaskDelegateStateType_MAX;
