// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class HEWSFindMessageTrackingSearchResultType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSArrayOfFindMessageTrackingSearchResultType : NSObject <PicoBindable> {

@private
    NSMutableArray *_messageTrackingSearchResult;

}


/**
 (public property)
 
 entry type : class HEWSFindMessageTrackingSearchResultType
*/

@property (nonatomic, retain) NSMutableArray *messageTrackingSearchResult;


@end
