// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSNonEmptyArrayOfItemChangesType.h"
#import "HEWSItemChangeType.h"

@implementation HEWSNonEmptyArrayOfItemChangesType

@synthesize itemChange = _itemChange;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"ItemChange" propertyName:@"itemChange" type:PICO_TYPE_OBJECT clazz:[HEWSItemChangeType class]];
    [map setObject:ps forKey:@"itemChange"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.itemChange = nil;
    [super dealloc];
}

@end
