// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class HEWSCalendarPermissionType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSArrayOfCalendarPermissionsType : NSObject <PicoBindable> {

@private
    NSMutableArray *_calendarPermission;

}


/**
 (public property)
 
 entry type : class HEWSCalendarPermissionType
*/

@property (nonatomic, retain) NSMutableArray *calendarPermission;


@end
