// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"



/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSUserConfigurationDictionaryObjectType : NSObject <PicoBindable> {

@private
    NSString *_type;
    NSMutableArray *_value;

}


/**
 (public property)
 
 type: string constant in HEWSUserConfigurationDictionaryObjectTypesType.h
*/
@property (nonatomic, retain) NSString *type;

/**
 (public property)
 
 entry type : NSString, wrapper for primitive string
*/

@property (nonatomic, retain) NSMutableArray *value;


@end
