// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSReplyBody.h"

@implementation HEWSReplyBody

@synthesize message = _message;
@synthesize lang = _lang;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Message" propertyName:@"message" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"message"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ATTRIBUTE xmlName:@"lang" propertyName:@"lang" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"lang"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.message = nil;
    self.lang = nil;
    [super dealloc];
}

@end
