// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSRecurringDayTransitionType.h"

@implementation HEWSRecurringDayTransitionType

@synthesize dayOfWeek = _dayOfWeek;
@synthesize occurrence = _occurrence;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    PicoClassSchema *cs = [[PicoClassSchema alloc] initWithXmlName:@"RecurringDayTransition" nsUri:@"http://schemas.microsoft.com/exchange/services/2006/types"];
    [cs autorelease];
    return cs;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"DayOfWeek" propertyName:@"dayOfWeek" type:PICO_TYPE_ENUM clazz:nil];
    [map setObject:ps forKey:@"dayOfWeek"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Occurrence" propertyName:@"occurrence" type:PICO_TYPE_INT clazz:nil];
    [map setObject:ps forKey:@"occurrence"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.dayOfWeek = nil;
    self.occurrence = nil;
    [super dealloc];
}

@end
