// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSNonEmptyArrayOfRequestAttachmentIdsType.h"
#import "HEWSRequestAttachmentIdType.h"

@implementation HEWSNonEmptyArrayOfRequestAttachmentIdsType

@synthesize attachmentId = _attachmentId;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"AttachmentId" propertyName:@"attachmentId" type:PICO_TYPE_OBJECT clazz:[HEWSRequestAttachmentIdType class]];
    [map setObject:ps forKey:@"attachmentId"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.attachmentId = nil;
    [super dealloc];
}

@end
