// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class HEWSElement;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSEncryptedDataContainerType : NSObject <PicoBindable> {

@private
    NSMutableArray *_any;

}


/**
 (public property)
 
 entry type : HEWSElement, wrapper for primitive object
*/
@property (nonatomic, retain) NSMutableArray *any;


@end
