// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>


extern NSString *const HEWSExceptionPropertyURIType_ATTACHMENT_NAME;

extern NSString *const HEWSExceptionPropertyURIType_ATTACHMENT_CONTENT_TYPE;

extern NSString *const HEWSExceptionPropertyURIType_ATTACHMENT_CONTENT;

extern NSString *const HEWSExceptionPropertyURIType_RECURRENCE_MONTH;

extern NSString *const HEWSExceptionPropertyURIType_RECURRENCE_DAY_OF_WEEK_INDEX;

extern NSString *const HEWSExceptionPropertyURIType_RECURRENCE_DAYS_OF_WEEK;

extern NSString *const HEWSExceptionPropertyURIType_RECURRENCE_DAY_OF_MONTH;

extern NSString *const HEWSExceptionPropertyURIType_RECURRENCE_INTERVAL;

extern NSString *const HEWSExceptionPropertyURIType_RECURRENCE_NUMBER_OF_OCCURRENCES;

extern NSString *const HEWSExceptionPropertyURIType_TIMEZONE_OFFSET;
