// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSMembersListType.h"
#import "HEWSMemberType.h"

@implementation HEWSMembersListType

@synthesize member = _member;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"Member" propertyName:@"member" type:PICO_TYPE_OBJECT clazz:[HEWSMemberType class]];
    [map setObject:ps forKey:@"member"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.member = nil;
    [super dealloc];
}

@end
