// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class HEWSSerializableTimeZone;
@class HEWSArrayOfWorkingPeriod;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSWorkingHours : NSObject <PicoBindable> {

@private
    HEWSSerializableTimeZone *_timeZone;
    HEWSArrayOfWorkingPeriod *_workingPeriodArray;

}


/**
 (public property)
 
 type : class HEWSSerializableTimeZone
*/
@property (nonatomic, retain) HEWSSerializableTimeZone *timeZone;

/**
 (public property)
 
 type : class HEWSArrayOfWorkingPeriod
*/
@property (nonatomic, retain) HEWSArrayOfWorkingPeriod *workingPeriodArray;


@end
