// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class HEWSBaseFolderIdType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSNonEmptyArrayOfBaseFolderIdsType : NSObject <PicoBindable> {

@private
    NSMutableArray *_folderIdOrDistinguishedFolderId;

}


/**
 (public property)
 
 entry type : class HEWSBaseFolderIdType
*/

@property (nonatomic, retain) NSMutableArray *folderIdOrDistinguishedFolderId;


@end
