// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import "HEWSSpecialLogonTypeType.h"

/**
 @file
 Surfaces the various logon types that are supported for conversion
*/

NSString *const HEWSSpecialLogonTypeType_ADMIN = @"Admin";

NSString *const HEWSSpecialLogonTypeType_SYSTEM_SERVICE = @"SystemService";
