// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import "HEWSDayOfWeekType.h"


NSString *const HEWSDayOfWeekType_SUNDAY = @"Sunday";

NSString *const HEWSDayOfWeekType_MONDAY = @"Monday";

NSString *const HEWSDayOfWeekType_TUESDAY = @"Tuesday";

NSString *const HEWSDayOfWeekType_WEDNESDAY = @"Wednesday";

NSString *const HEWSDayOfWeekType_THURSDAY = @"Thursday";

NSString *const HEWSDayOfWeekType_FRIDAY = @"Friday";

NSString *const HEWSDayOfWeekType_SATURDAY = @"Saturday";

NSString *const HEWSDayOfWeekType_DAY = @"Day";

NSString *const HEWSDayOfWeekType_WEEKDAY = @"Weekday";

NSString *const HEWSDayOfWeekType_WEEKEND_DAY = @"WeekendDay";
