// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class HEWSOutOfOfficeMailTip;
@class HEWSEmailAddressType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSMailTips : NSObject <PicoBindable> {

@private
    HEWSEmailAddressType *_recipientAddress;
    NSMutableArray *_pendingMailTips;
    HEWSOutOfOfficeMailTip *_outOfOffice;
    NSNumber *_mailboxFull;
    NSString *_customMailTip;
    NSNumber *_totalMemberCount;
    NSNumber *_externalMemberCount;
    NSNumber *_maxMessageSize;
    NSNumber *_deliveryRestricted;
    NSNumber *_isModerated;
    NSNumber *_invalidRecipient;

}


/**
 (public property)
 
 type : class HEWSEmailAddressType
*/
@property (nonatomic, retain) HEWSEmailAddressType *recipientAddress;

/**
 (public property)
 
 entry type : NSString, wrapper for primitive string
*/

@property (nonatomic, retain) NSMutableArray *pendingMailTips;

/**
 (public property)
 
 type : class HEWSOutOfOfficeMailTip
*/
@property (nonatomic, retain) HEWSOutOfOfficeMailTip *outOfOffice;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *mailboxFull;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *customMailTip;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *totalMemberCount;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *externalMemberCount;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *maxMessageSize;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *deliveryRestricted;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *isModerated;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *invalidRecipient;


@end
