// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import "HEWSDistinguishedPropertySetType.h"

/**
 @file
 
         Defines the well known property set ids for extended properties.
       
*/

NSString *const HEWSDistinguishedPropertySetType_MEETING = @"Meeting";

NSString *const HEWSDistinguishedPropertySetType_APPOINTMENT = @"Appointment";

NSString *const HEWSDistinguishedPropertySetType_COMMON = @"Common";

NSString *const HEWSDistinguishedPropertySetType_PUBLIC_STRINGS = @"PublicStrings";

NSString *const HEWSDistinguishedPropertySetType_ADDRESS = @"Address";

NSString *const HEWSDistinguishedPropertySetType_INTERNET_HEADERS = @"InternetHeaders";

NSString *const HEWSDistinguishedPropertySetType_CALENDAR_ASSISTANT = @"CalendarAssistant";

NSString *const HEWSDistinguishedPropertySetType_UNIFIED_MESSAGING = @"UnifiedMessaging";

NSString *const HEWSDistinguishedPropertySetType_TASK = @"Task";
