// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class HEWSDuration;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSSuggestionsViewOptionsType : NSObject <PicoBindable> {

@private
    NSNumber *_goodThreshold;
    NSNumber *_maximumResultsByDay;
    NSNumber *_maximumNonWorkHourResultsByDay;
    NSNumber *_meetingDurationInMinutes;
    NSString *_minimumSuggestionQuality;
    HEWSDuration *_detailedSuggestionsWindow;
    NSDate *_currentMeetingTime;
    NSString *_globalObjectId;

}


/**
 (public property)
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *goodThreshold;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *maximumResultsByDay;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *maximumNonWorkHourResultsByDay;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *meetingDurationInMinutes;

/**
 (public property)
 
 type: string constant in HEWSSuggestionQuality.h
*/
@property (nonatomic, retain) NSString *minimumSuggestionQuality;

/**
 (public property)
 
 type : class HEWSDuration
*/
@property (nonatomic, retain) HEWSDuration *detailedSuggestionsWindow;

/**
 (public property)
 
 type : NSDate, wrapper for primitive date
*/
@property (nonatomic, retain) NSDate *currentMeetingTime;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *globalObjectId;


@end
