// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class HEWSArrayOfAttendeeConflictData;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSSuggestion : NSObject <PicoBindable> {

@private
    NSDate *_meetingTime;
    NSNumber *_isWorkTime;
    NSString *_suggestionQuality;
    HEWSArrayOfAttendeeConflictData *_attendeeConflictDataArray;

}


/**
 (public property)
 
 type : NSDate, wrapper for primitive date
*/
@property (nonatomic, retain) NSDate *meetingTime;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *isWorkTime;

/**
 (public property)
 
 type: string constant in HEWSSuggestionQuality.h
*/
@property (nonatomic, retain) NSString *suggestionQuality;

/**
 (public property)
 
 type : class HEWSArrayOfAttendeeConflictData
*/
@property (nonatomic, retain) HEWSArrayOfAttendeeConflictData *attendeeConflictDataArray;


@end
