// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class HEWSMailboxData;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSArrayOfMailboxData : NSObject <PicoBindable> {

@private
    NSMutableArray *_mailboxData;

}


/**
 (public property)
 
 entry type : class HEWSMailboxData
*/

@property (nonatomic, retain) NSMutableArray *mailboxData;


@end
