// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import "HEWSFileAsMappingType.h"


NSString *const HEWSFileAsMappingType_NONE = @"None";

NSString *const HEWSFileAsMappingType_LAST_COMMA_FIRST = @"LastCommaFirst";

NSString *const HEWSFileAsMappingType_FIRST_SPACE_LAST = @"FirstSpaceLast";

NSString *const HEWSFileAsMappingType_COMPANY = @"Company";

NSString *const HEWSFileAsMappingType_LAST_COMMA_FIRST_COMPANY = @"LastCommaFirstCompany";

NSString *const HEWSFileAsMappingType_COMPANY_LAST_FIRST = @"CompanyLastFirst";

NSString *const HEWSFileAsMappingType_LAST_FIRST = @"LastFirst";

NSString *const HEWSFileAsMappingType_LAST_FIRST_COMPANY = @"LastFirstCompany";

NSString *const HEWSFileAsMappingType_COMPANY_LAST_COMMA_FIRST = @"CompanyLastCommaFirst";

NSString *const HEWSFileAsMappingType_LAST_FIRST_SUFFIX = @"LastFirstSuffix";

NSString *const HEWSFileAsMappingType_LAST_SPACE_FIRST_COMPANY = @"LastSpaceFirstCompany";

NSString *const HEWSFileAsMappingType_COMPANY_LAST_SPACE_FIRST = @"CompanyLastSpaceFirst";

NSString *const HEWSFileAsMappingType_LAST_SPACE_FIRST = @"LastSpaceFirst";

NSString *const HEWSFileAsMappingType_DISPLAY_NAME = @"DisplayName";

NSString *const HEWSFileAsMappingType_FIRST_NAME = @"FirstName";

NSString *const HEWSFileAsMappingType_LAST_FIRST_MIDDLE_SUFFIX = @"LastFirstMiddleSuffix";

NSString *const HEWSFileAsMappingType_LAST_NAME = @"LastName";

NSString *const HEWSFileAsMappingType_EMPTY = @"Empty";
