// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSProtectionRuleType.h"
#import "HEWSProtectionRuleActionType.h"
#import "HEWSProtectionRuleConditionType.h"

@implementation HEWSProtectionRuleType

@synthesize condition = _condition;
@synthesize action = _action;
@synthesize name = _name;
@synthesize userOverridable = _userOverridable;
@synthesize priority = _priority;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Condition" propertyName:@"condition" type:PICO_TYPE_OBJECT clazz:[HEWSProtectionRuleConditionType class]];
    [map setObject:ps forKey:@"condition"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Action" propertyName:@"action" type:PICO_TYPE_OBJECT clazz:[HEWSProtectionRuleActionType class]];
    [map setObject:ps forKey:@"action"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ATTRIBUTE xmlName:@"Name" propertyName:@"name" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"name"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ATTRIBUTE xmlName:@"UserOverridable" propertyName:@"userOverridable" type:PICO_TYPE_BOOL clazz:nil];
    [map setObject:ps forKey:@"userOverridable"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ATTRIBUTE xmlName:@"Priority" propertyName:@"priority" type:PICO_TYPE_INT clazz:nil];
    [map setObject:ps forKey:@"priority"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.condition = nil;
    self.action = nil;
    self.name = nil;
    self.userOverridable = nil;
    self.priority = nil;
    [super dealloc];
}

@end
