// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSSerializableTimeZoneTime.h"

@implementation HEWSSerializableTimeZoneTime

@synthesize bias = _bias;
@synthesize time = _time;
@synthesize dayOrder = _dayOrder;
@synthesize month = _month;
@synthesize dayOfWeek = _dayOfWeek;
@synthesize year = _year;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Bias" propertyName:@"bias" type:PICO_TYPE_INT clazz:nil];
    [map setObject:ps forKey:@"bias"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Time" propertyName:@"time" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"time"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"DayOrder" propertyName:@"dayOrder" type:PICO_TYPE_SHORT clazz:nil];
    [map setObject:ps forKey:@"dayOrder"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Month" propertyName:@"month" type:PICO_TYPE_SHORT clazz:nil];
    [map setObject:ps forKey:@"month"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"DayOfWeek" propertyName:@"dayOfWeek" type:PICO_TYPE_ENUM clazz:nil];
    [map setObject:ps forKey:@"dayOfWeek"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Year" propertyName:@"year" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"year"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.bias = nil;
    self.time = nil;
    self.dayOrder = nil;
    self.month = nil;
    self.dayOfWeek = nil;
    self.year = nil;
    [super dealloc];
}

@end
