// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSExcludesType.h"
#import "HEWSJAXBElement<? extends BasePathToElementType>.h"
#import "HEWSExcludesValueType.h"

@implementation HEWSExcludesType

@synthesize path = _path;
@synthesize bitmask = _bitmask;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    PicoClassSchema *cs = [[PicoClassSchema alloc] initWithXmlName:@"Excludes" nsUri:@"http://schemas.microsoft.com/exchange/services/2006/types"];
    [cs autorelease];
    return cs;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ANY_ELEMENT xmlName:@"path" propertyName:@"path" type:PICO_TYPE_OBJECT clazz:[HEWSJAXBElement<? extends BasePathToElementType> class]];
    [map setObject:ps forKey:@"path"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Bitmask" propertyName:@"bitmask" type:PICO_TYPE_OBJECT clazz:[HEWSExcludesValueType class]];
    [map setObject:ps forKey:@"bitmask"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.path = nil;
    self.bitmask = nil;
    [super dealloc];
}

@end
