// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import "HEWSAggregateType.h"

/**
 @file
 
         This max/min evaluation is applied to the field specified within the group by
         instance for EACH item within that group.  This determines which item from each group
         is to be selected as the representative for that group.
       
*/

NSString *const HEWSAggregateType_MINIMUM = @"Minimum";

NSString *const HEWSAggregateType_MAXIMUM = @"Maximum";
