// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "HEWSTargetFolderIdType.h"



/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSUserConfigurationNameType : HEWSTargetFolderIdType {

@private
    NSString *_name;

}


/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *name;


@end
