// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import "HEWSCompleteActionType.h"


NSString *const HEWSCompleteActionType_COMMIT = @"Commit";

NSString *const HEWSCompleteActionType_ABANDON = @"Abandon";
