// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class HEWSAttendeeType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSNonEmptyArrayOfAttendeesType : NSObject <PicoBindable> {

@private
    NSMutableArray *_attendee;

}


/**
 (public property)
 
 entry type : class HEWSAttendeeType
*/

@property (nonatomic, retain) NSMutableArray *attendee;


@end
