// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSNotificationType.h"

@implementation HEWSNotificationType

@synthesize subscriptionId = _subscriptionId;
@synthesize previousWatermark = _previousWatermark;
@synthesize moreEvents = _moreEvents;
@synthesize copiedEventOrCreatedEventOrDeletedEvent = _copiedEventOrCreatedEventOrDeletedEvent;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"SubscriptionId" propertyName:@"subscriptionId" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"subscriptionId"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"PreviousWatermark" propertyName:@"previousWatermark" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"previousWatermark"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"MoreEvents" propertyName:@"moreEvents" type:PICO_TYPE_BOOL clazz:nil];
    [map setObject:ps forKey:@"moreEvents"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ANY_ELEMENT xmlName:@"copiedEventOrCreatedEventOrDeletedEvent" propertyName:@"copiedEventOrCreatedEventOrDeletedEvent" type:PICO_TYPE_OBJECT clazz:[HEWSJAXBElement<? extends BaseNotificationEventType> class]];
    [map setObject:ps forKey:@"copiedEventOrCreatedEventOrDeletedEvent"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.subscriptionId = nil;
    self.previousWatermark = nil;
    self.moreEvents = nil;
    self.copiedEventOrCreatedEventOrDeletedEvent = nil;
    [super dealloc];
}

@end
