// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSModifiedEventType.h"

@implementation HEWSModifiedEventType

@synthesize unreadCount = _unreadCount;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    PicoClassSchema *cs = [[PicoClassSchema alloc] initWithXmlName:@"ModifiedEvent" nsUri:@"http://schemas.microsoft.com/exchange/services/2006/types"];
    [cs autorelease];
    return cs;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"UnreadCount" propertyName:@"unreadCount" type:PICO_TYPE_INT clazz:nil];
    [map setObject:ps forKey:@"unreadCount"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.unreadCount = nil;
    [super dealloc];
}

@end
