// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSTimeZoneType.h"
#import "HEWSTimeChangeType.h"

@implementation HEWSTimeZoneType

@synthesize baseOffset = _baseOffset;
@synthesize standard = _standard;
@synthesize daylight = _daylight;
@synthesize timeZoneName = _timeZoneName;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"BaseOffset" propertyName:@"baseOffset" type:PICO_TYPE_DURATION clazz:nil];
    [map setObject:ps forKey:@"baseOffset"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Standard" propertyName:@"standard" type:PICO_TYPE_OBJECT clazz:[HEWSTimeChangeType class]];
    [map setObject:ps forKey:@"standard"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Daylight" propertyName:@"daylight" type:PICO_TYPE_OBJECT clazz:[HEWSTimeChangeType class]];
    [map setObject:ps forKey:@"daylight"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ATTRIBUTE xmlName:@"TimeZoneName" propertyName:@"timeZoneName" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"timeZoneName"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.baseOffset = nil;
    self.standard = nil;
    self.daylight = nil;
    self.timeZoneName = nil;
    [super dealloc];
}

@end
