// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import "HEWSDayOfWeekIndexType.h"


NSString *const HEWSDayOfWeekIndexType_FIRST = @"First";

NSString *const HEWSDayOfWeekIndexType_SECOND = @"Second";

NSString *const HEWSDayOfWeekIndexType_THIRD = @"Third";

NSString *const HEWSDayOfWeekIndexType_FOURTH = @"Fourth";

NSString *const HEWSDayOfWeekIndexType_LAST = @"Last";
