// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class HEWSItemType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSNonEmptyArrayOfAllItemsType : NSObject <PicoBindable> {

@private
    NSMutableArray *_itemOrMessageOrCalendarItem;

}


/**
 (public property)
 
 entry type : class HEWSItemType
*/

@property (nonatomic, retain) NSMutableArray *itemOrMessageOrCalendarItem;


@end
