// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import "HEWSDisposalType.h"


NSString *const HEWSDisposalType_HARD_DELETE = @"HardDelete";

NSString *const HEWSDisposalType_SOFT_DELETE = @"SoftDelete";

NSString *const HEWSDisposalType_MOVE_TO_DELETED_ITEMS = @"MoveToDeletedItems";
