// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class HEWSFolderChangeType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSNonEmptyArrayOfFolderChangesType : NSObject <PicoBindable> {

@private
    NSMutableArray *_folderChange;

}


/**
 (public property)
 
 entry type : class HEWSFolderChangeType
*/

@property (nonatomic, retain) NSMutableArray *folderChange;


@end
