// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "HEWSBaseItemIdType.h"



/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSRecurringMasterItemIdType : HEWSBaseItemIdType {

@private
    NSString *_occurrenceId;
    NSString *_changeKey;

}


/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *occurrenceId;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *changeKey;


@end
