// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "HEWSSearchExpressionType.h"

// abstract class


/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSMultipleOperandBooleanExpressionType : HEWSSearchExpressionType {

@private
    NSMutableArray *_searchExpression;

}


/**
 (public property)
 
 entry type : class HEWSJAXBElement<? extends SearchExpressionType>
*/

@property (nonatomic, retain) NSMutableArray *searchExpression;


@end
