// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import "HEWSNotificationEventTypeType.h"


NSString *const HEWSNotificationEventTypeType_COPIED_EVENT = @"CopiedEvent";

NSString *const HEWSNotificationEventTypeType_CREATED_EVENT = @"CreatedEvent";

NSString *const HEWSNotificationEventTypeType_DELETED_EVENT = @"DeletedEvent";

NSString *const HEWSNotificationEventTypeType_MODIFIED_EVENT = @"ModifiedEvent";

NSString *const HEWSNotificationEventTypeType_MOVED_EVENT = @"MovedEvent";

NSString *const HEWSNotificationEventTypeType_NEW_MAIL_EVENT = @"NewMailEvent";

NSString *const HEWSNotificationEventTypeType_FREE_BUSY_CHANGED_EVENT = @"FreeBusyChangedEvent";
