// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"



/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSInvalidRecipientType : NSObject <PicoBindable> {

@private
    NSString *_smtpAddress;
    NSString *_responseCode;
    NSString *_messageText;

}


/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *smtpAddress;

/**
 (public property)
 
 type: string constant in HEWSInvalidRecipientResponseCodeType.h
*/
@property (nonatomic, retain) NSString *responseCode;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *messageText;


@end
