// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class HEWSMemberType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSMembersListType : NSObject <PicoBindable> {

@private
    NSMutableArray *_member;

}


/**
 (public property)
 
 entry type : class HEWSMemberType
*/

@property (nonatomic, retain) NSMutableArray *member;


@end
