// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "HEWSBaseFolderIdType.h"



/**
 Identifier for a fully resolved folder
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSFolderIdType : HEWSBaseFolderIdType {

@private
    NSString *_id;
    NSString *_changeKey;

}


/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *id;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *changeKey;


@end
