// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class HEWSProtectionRuleArgumentType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSProtectionRuleActionType : NSObject <PicoBindable> {

@private
    NSMutableArray *_argument;
    NSString *_name;

}


/**
 (public property)
 
 entry type : class HEWSProtectionRuleArgumentType
*/

@property (nonatomic, retain) NSMutableArray *argument;

/**
 (public property)
 
 type: string constant in HEWSProtectionRuleActionKindType.h
*/
@property (nonatomic, retain) NSString *name;


@end
