// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "HEWSBasePagingType.h"



/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSFractionalPageViewType : HEWSBasePagingType {

@private
    NSNumber *_numerator;
    NSNumber *_denominator;

}


/**
 (public property)
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *numerator;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *denominator;


@end
