// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import "HEWSIdFormatType.h"

/**
 @file
 Surfaces the various id types that are supported for conversion
*/

NSString *const HEWSIdFormatType_EWS_LEGACY_ID = @"EwsLegacyId";

NSString *const HEWSIdFormatType_EWS_ID = @"EwsId";

NSString *const HEWSIdFormatType_ENTRY_ID = @"EntryId";

NSString *const HEWSIdFormatType_HEX_ENTRY_ID = @"HexEntryId";

NSString *const HEWSIdFormatType_STORE_ID = @"StoreId";

NSString *const HEWSIdFormatType_OWA_ID = @"OwaId";
