// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"



/**
 Compound property for Managed Folder related information for Managed Folders.
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSManagedFolderInformationType : NSObject <PicoBindable> {

@private
    NSNumber *_canDelete;
    NSNumber *_canRenameOrMove;
    NSNumber *_mustDisplayComment;
    NSNumber *_hasQuota;
    NSNumber *_isManagedFoldersRoot;
    NSString *_managedFolderId;
    NSString *_comment;
    NSNumber *_storageQuota;
    NSNumber *_folderSize;
    NSString *_homePage;

}


/**
 (public property)
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *canDelete;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *canRenameOrMove;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *mustDisplayComment;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *hasQuota;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *isManagedFoldersRoot;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *managedFolderId;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *comment;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *storageQuota;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *folderSize;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *homePage;


@end
