// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>


extern NSString *const HEWSImAddressKeyType_IM_ADDRESS_1;

extern NSString *const HEWSImAddressKeyType_IM_ADDRESS_2;

extern NSString *const HEWSImAddressKeyType_IM_ADDRESS_3;
