// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>


extern NSString *const HEWSCalendarItemUpdateOperationType_SEND_TO_NONE;

extern NSString *const HEWSCalendarItemUpdateOperationType_SEND_ONLY_TO_ALL;

extern NSString *const HEWSCalendarItemUpdateOperationType_SEND_ONLY_TO_CHANGED;

extern NSString *const HEWSCalendarItemUpdateOperationType_SEND_TO_ALL_AND_SAVE_COPY;

extern NSString *const HEWSCalendarItemUpdateOperationType_SEND_TO_CHANGED_AND_SAVE_COPY;
