// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "HEWSRecurrencePatternBaseType.h"

// abstract class


/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSIntervalRecurrencePatternBaseType : HEWSRecurrencePatternBaseType {

@private
    NSNumber *_interval;

}


/**
 (public property)
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *interval;


@end
