// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSNonEmptyArrayOfDeletedOccurrencesType.h"
#import "HEWSDeletedOccurrenceInfoType.h"

@implementation HEWSNonEmptyArrayOfDeletedOccurrencesType

@synthesize deletedOccurrence = _deletedOccurrence;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"DeletedOccurrence" propertyName:@"deletedOccurrence" type:PICO_TYPE_OBJECT clazz:[HEWSDeletedOccurrenceInfoType class]];
    [map setObject:ps forKey:@"deletedOccurrence"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.deletedOccurrence = nil;
    [super dealloc];
}

@end
