// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSTimeChangeType.h"
#import "HEWSRelativeYearlyRecurrencePatternType.h"

@implementation HEWSTimeChangeType

@synthesize offset = _offset;
@synthesize relativeYearlyRecurrence = _relativeYearlyRecurrence;
@synthesize absoluteDate = _absoluteDate;
@synthesize time = _time;
@synthesize timeZoneName = _timeZoneName;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Offset" propertyName:@"offset" type:PICO_TYPE_DURATION clazz:nil];
    [map setObject:ps forKey:@"offset"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"RelativeYearlyRecurrence" propertyName:@"relativeYearlyRecurrence" type:PICO_TYPE_OBJECT clazz:[HEWSRelativeYearlyRecurrencePatternType class]];
    [map setObject:ps forKey:@"relativeYearlyRecurrence"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"AbsoluteDate" propertyName:@"absoluteDate" type:PICO_TYPE_DATE clazz:nil];
    [map setObject:ps forKey:@"absoluteDate"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Time" propertyName:@"time" type:PICO_TYPE_DATE clazz:nil];
    [map setObject:ps forKey:@"time"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ATTRIBUTE xmlName:@"TimeZoneName" propertyName:@"timeZoneName" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"timeZoneName"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.offset = nil;
    self.relativeYearlyRecurrence = nil;
    self.absoluteDate = nil;
    self.time = nil;
    self.timeZoneName = nil;
    [super dealloc];
}

@end
