// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import "HEWSDateTimePrecisionType.h"

/**
 @file
 Precision for returned DateTime values
*/

NSString *const HEWSDateTimePrecisionType_SECONDS = @"Seconds";

NSString *const HEWSDateTimePrecisionType_MILLISECONDS = @"Milliseconds";
