// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "HEWSBasePagingType.h"



/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSCalendarViewType : HEWSBasePagingType {

@private
    NSDate *_startDate;
    NSDate *_endDate;

}


/**
 (public property)
 
 type : NSDate, wrapper for primitive date
*/
@property (nonatomic, retain) NSDate *startDate;

/**
 (public property)
 
 type : NSDate, wrapper for primitive date
*/
@property (nonatomic, retain) NSDate *endDate;


@end
