// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>


extern NSString *const HEWSConnectionFailureCauseType_NONE;

extern NSString *const HEWSConnectionFailureCauseType_USER_BUSY;

extern NSString *const HEWSConnectionFailureCauseType_NO_ANSWER;

extern NSString *const HEWSConnectionFailureCauseType_UNAVAILABLE;

extern NSString *const HEWSConnectionFailureCauseType_OTHER;
