// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSPathToExtendedFieldType.h"

@implementation HEWSPathToExtendedFieldType

@synthesize distinguishedPropertySetId = _distinguishedPropertySetId;
@synthesize propertySetId = _propertySetId;
@synthesize propertyTag = _propertyTag;
@synthesize propertyName = _propertyName;
@synthesize propertyId = _propertyId;
@synthesize propertyType = _propertyType;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    PicoClassSchema *cs = [[PicoClassSchema alloc] initWithXmlName:@"ExtendedFieldURI" nsUri:@"http://schemas.microsoft.com/exchange/services/2006/types"];
    [cs autorelease];
    return cs;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ATTRIBUTE xmlName:@"DistinguishedPropertySetId" propertyName:@"distinguishedPropertySetId" type:PICO_TYPE_ENUM clazz:nil];
    [map setObject:ps forKey:@"distinguishedPropertySetId"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ATTRIBUTE xmlName:@"PropertySetId" propertyName:@"propertySetId" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"propertySetId"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ATTRIBUTE xmlName:@"PropertyTag" propertyName:@"propertyTag" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"propertyTag"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ATTRIBUTE xmlName:@"PropertyName" propertyName:@"propertyName" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"propertyName"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ATTRIBUTE xmlName:@"PropertyId" propertyName:@"propertyId" type:PICO_TYPE_INT clazz:nil];
    [map setObject:ps forKey:@"propertyId"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ATTRIBUTE xmlName:@"PropertyType" propertyName:@"propertyType" type:PICO_TYPE_ENUM clazz:nil];
    [map setObject:ps forKey:@"propertyType"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.distinguishedPropertySetId = nil;
    self.propertySetId = nil;
    self.propertyTag = nil;
    self.propertyName = nil;
    self.propertyId = nil;
    self.propertyType = nil;
    [super dealloc];
}

@end
