// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSOccurrenceItemIdType.h"

@implementation HEWSOccurrenceItemIdType

@synthesize recurringMasterId = _recurringMasterId;
@synthesize changeKey = _changeKey;
@synthesize instanceIndex = _instanceIndex;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ATTRIBUTE xmlName:@"RecurringMasterId" propertyName:@"recurringMasterId" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"recurringMasterId"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ATTRIBUTE xmlName:@"ChangeKey" propertyName:@"changeKey" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"changeKey"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ATTRIBUTE xmlName:@"InstanceIndex" propertyName:@"instanceIndex" type:PICO_TYPE_INT clazz:nil];
    [map setObject:ps forKey:@"instanceIndex"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.recurringMasterId = nil;
    self.changeKey = nil;
    self.instanceIndex = nil;
    [super dealloc];
}

@end
