// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import "HEWSRuleValidationErrorCodeType.h"

/**
 @file
 Rule validation error code describing what failed validation for each rule predicate or action.
*/

NSString *const HEWSRuleValidationErrorCodeType_AD_OPERATION_FAILURE = @"ADOperationFailure";

NSString *const HEWSRuleValidationErrorCodeType_CONNECTED_ACCOUNT_NOT_FOUND = @"ConnectedAccountNotFound";

NSString *const HEWSRuleValidationErrorCodeType_CREATE_WITH_RULE_ID = @"CreateWithRuleId";

NSString *const HEWSRuleValidationErrorCodeType_EMPTY_VALUE_FOUND = @"EmptyValueFound";

NSString *const HEWSRuleValidationErrorCodeType_DUPLICATED_PRIORITY = @"DuplicatedPriority";

NSString *const HEWSRuleValidationErrorCodeType_DUPLICATED_OPERATION_ON_THE_SAME_RULE = @"DuplicatedOperationOnTheSameRule";

NSString *const HEWSRuleValidationErrorCodeType_FOLDER_DOES_NOT_EXIST = @"FolderDoesNotExist";

NSString *const HEWSRuleValidationErrorCodeType_INVALID_ADDRESS = @"InvalidAddress";

NSString *const HEWSRuleValidationErrorCodeType_INVALID_DATE_RANGE = @"InvalidDateRange";

NSString *const HEWSRuleValidationErrorCodeType_INVALID_FOLDER_ID = @"InvalidFolderId";

NSString *const HEWSRuleValidationErrorCodeType_INVALID_SIZE_RANGE = @"InvalidSizeRange";

NSString *const HEWSRuleValidationErrorCodeType_INVALID_VALUE = @"InvalidValue";

NSString *const HEWSRuleValidationErrorCodeType_MESSAGE_CLASSIFICATION_NOT_FOUND = @"MessageClassificationNotFound";

NSString *const HEWSRuleValidationErrorCodeType_MISSING_ACTION = @"MissingAction";

NSString *const HEWSRuleValidationErrorCodeType_MISSING_PARAMETER = @"MissingParameter";

NSString *const HEWSRuleValidationErrorCodeType_MISSING_RANGE_VALUE = @"MissingRangeValue";

NSString *const HEWSRuleValidationErrorCodeType_NOT_SETTABLE = @"NotSettable";

NSString *const HEWSRuleValidationErrorCodeType_RECIPIENT_DOES_NOT_EXIST = @"RecipientDoesNotExist";

NSString *const HEWSRuleValidationErrorCodeType_RULE_NOT_FOUND = @"RuleNotFound";

NSString *const HEWSRuleValidationErrorCodeType_SIZE_LESS_THAN_ZERO = @"SizeLessThanZero";

NSString *const HEWSRuleValidationErrorCodeType_STRING_VALUE_TOO_BIG = @"StringValueTooBig";

NSString *const HEWSRuleValidationErrorCodeType_UNSUPPORTED_ADDRESS = @"UnsupportedAddress";

NSString *const HEWSRuleValidationErrorCodeType_UNEXPECTED_ERROR = @"UnexpectedError";

NSString *const HEWSRuleValidationErrorCodeType_UNSUPPORTED_RULE = @"UnsupportedRule";
