// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSSmtpDomainList.h"
#import "HEWSSmtpDomain.h"

@implementation HEWSSmtpDomainList

@synthesize domain = _domain;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"Domain" propertyName:@"domain" type:PICO_TYPE_OBJECT clazz:[HEWSSmtpDomain class]];
    [map setObject:ps forKey:@"domain"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.domain = nil;
    [super dealloc];
}

@end
