// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSGroupByType.h"
#import "HEWSPathToUnindexedFieldType.h"
#import "HEWSPathToExtendedFieldType.h"
#import "HEWSAggregateOnType.h"
#import "HEWSPathToIndexedFieldType.h"

@implementation HEWSGroupByType

@synthesize fieldURI = _fieldURI;
@synthesize indexedFieldURI = _indexedFieldURI;
@synthesize extendedFieldURI = _extendedFieldURI;
@synthesize aggregateOn = _aggregateOn;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"FieldURI" propertyName:@"fieldURI" type:PICO_TYPE_OBJECT clazz:[HEWSPathToUnindexedFieldType class]];
    [map setObject:ps forKey:@"fieldURI"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"IndexedFieldURI" propertyName:@"indexedFieldURI" type:PICO_TYPE_OBJECT clazz:[HEWSPathToIndexedFieldType class]];
    [map setObject:ps forKey:@"indexedFieldURI"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ExtendedFieldURI" propertyName:@"extendedFieldURI" type:PICO_TYPE_OBJECT clazz:[HEWSPathToExtendedFieldType class]];
    [map setObject:ps forKey:@"extendedFieldURI"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"AggregateOn" propertyName:@"aggregateOn" type:PICO_TYPE_OBJECT clazz:[HEWSAggregateOnType class]];
    [map setObject:ps forKey:@"aggregateOn"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.fieldURI = nil;
    self.indexedFieldURI = nil;
    self.extendedFieldURI = nil;
    self.aggregateOn = nil;
    [super dealloc];
}

@end
