// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSRulePredicateSizeRangeType.h"

@implementation HEWSRulePredicateSizeRangeType

@synthesize minimumSize = _minimumSize;
@synthesize maximumSize = _maximumSize;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"MinimumSize" propertyName:@"minimumSize" type:PICO_TYPE_INT clazz:nil];
    [map setObject:ps forKey:@"minimumSize"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"MaximumSize" propertyName:@"maximumSize" type:PICO_TYPE_INT clazz:nil];
    [map setObject:ps forKey:@"maximumSize"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.minimumSize = nil;
    self.maximumSize = nil;
    [super dealloc];
}

@end
