// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class HEWSPeriodType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSNonEmptyArrayOfPeriodsType : NSObject <PicoBindable> {

@private
    NSMutableArray *_period;

}


/**
 (public property)
 
 entry type : class HEWSPeriodType
*/

@property (nonatomic, retain) NSMutableArray *period;


@end
