// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>

/**
 @file
 Rule validation error code describing what failed validation for each rule predicate or action.
 
 @ingroup ExchangeServicePortType
*/

extern NSString *const HEWSRuleValidationErrorCodeType_AD_OPERATION_FAILURE;

extern NSString *const HEWSRuleValidationErrorCodeType_CONNECTED_ACCOUNT_NOT_FOUND;

extern NSString *const HEWSRuleValidationErrorCodeType_CREATE_WITH_RULE_ID;

extern NSString *const HEWSRuleValidationErrorCodeType_EMPTY_VALUE_FOUND;

extern NSString *const HEWSRuleValidationErrorCodeType_DUPLICATED_PRIORITY;

extern NSString *const HEWSRuleValidationErrorCodeType_DUPLICATED_OPERATION_ON_THE_SAME_RULE;

extern NSString *const HEWSRuleValidationErrorCodeType_FOLDER_DOES_NOT_EXIST;

extern NSString *const HEWSRuleValidationErrorCodeType_INVALID_ADDRESS;

extern NSString *const HEWSRuleValidationErrorCodeType_INVALID_DATE_RANGE;

extern NSString *const HEWSRuleValidationErrorCodeType_INVALID_FOLDER_ID;

extern NSString *const HEWSRuleValidationErrorCodeType_INVALID_SIZE_RANGE;

extern NSString *const HEWSRuleValidationErrorCodeType_INVALID_VALUE;

extern NSString *const HEWSRuleValidationErrorCodeType_MESSAGE_CLASSIFICATION_NOT_FOUND;

extern NSString *const HEWSRuleValidationErrorCodeType_MISSING_ACTION;

extern NSString *const HEWSRuleValidationErrorCodeType_MISSING_PARAMETER;

extern NSString *const HEWSRuleValidationErrorCodeType_MISSING_RANGE_VALUE;

extern NSString *const HEWSRuleValidationErrorCodeType_NOT_SETTABLE;

extern NSString *const HEWSRuleValidationErrorCodeType_RECIPIENT_DOES_NOT_EXIST;

extern NSString *const HEWSRuleValidationErrorCodeType_RULE_NOT_FOUND;

extern NSString *const HEWSRuleValidationErrorCodeType_SIZE_LESS_THAN_ZERO;

extern NSString *const HEWSRuleValidationErrorCodeType_STRING_VALUE_TOO_BIG;

extern NSString *const HEWSRuleValidationErrorCodeType_UNSUPPORTED_ADDRESS;

extern NSString *const HEWSRuleValidationErrorCodeType_UNEXPECTED_ERROR;

extern NSString *const HEWSRuleValidationErrorCodeType_UNSUPPORTED_RULE;
