// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSArrayOfArraysOfTrackingPropertiesType.h"
#import "HEWSArrayOfTrackingPropertiesType.h"

@implementation HEWSArrayOfArraysOfTrackingPropertiesType

@synthesize arrayOfTrackingPropertiesType = _arrayOfTrackingPropertiesType;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"ArrayOfTrackingPropertiesType" propertyName:@"arrayOfTrackingPropertiesType" type:PICO_TYPE_OBJECT clazz:[HEWSArrayOfTrackingPropertiesType class]];
    [map setObject:ps forKey:@"arrayOfTrackingPropertiesType"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.arrayOfTrackingPropertiesType = nil;
    [super dealloc];
}

@end
