// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class HEWSFieldOrderType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSNonEmptyArrayOfFieldOrdersType : NSObject <PicoBindable> {

@private
    NSMutableArray *_fieldOrder;

}


/**
 (public property)
 
 entry type : class HEWSFieldOrderType
*/

@property (nonatomic, retain) NSMutableArray *fieldOrder;


@end
