// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class HEWSDuration;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSFreeBusyViewOptionsType : NSObject <PicoBindable> {

@private
    HEWSDuration *_timeWindow;
    NSNumber *_mergedFreeBusyIntervalInMinutes;
    NSMutableArray *_requestedView;

}


/**
 (public property)
 
 type : class HEWSDuration
*/
@property (nonatomic, retain) HEWSDuration *timeWindow;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *mergedFreeBusyIntervalInMinutes;

/**
 (public property)
 
 entry type : NSString, wrapper for primitive string
*/

@property (nonatomic, retain) NSMutableArray *requestedView;


@end
