// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import "HEWSPhoneNumberKeyType.h"


NSString *const HEWSPhoneNumberKeyType_ASSISTANT_PHONE = @"AssistantPhone";

NSString *const HEWSPhoneNumberKeyType_BUSINESS_FAX = @"BusinessFax";

NSString *const HEWSPhoneNumberKeyType_BUSINESS_PHONE = @"BusinessPhone";

NSString *const HEWSPhoneNumberKeyType_BUSINESS_PHONE_2 = @"BusinessPhone2";

NSString *const HEWSPhoneNumberKeyType_CALLBACK = @"Callback";

NSString *const HEWSPhoneNumberKeyType_CAR_PHONE = @"CarPhone";

NSString *const HEWSPhoneNumberKeyType_COMPANY_MAIN_PHONE = @"CompanyMainPhone";

NSString *const HEWSPhoneNumberKeyType_HOME_FAX = @"HomeFax";

NSString *const HEWSPhoneNumberKeyType_HOME_PHONE = @"HomePhone";

NSString *const HEWSPhoneNumberKeyType_HOME_PHONE_2 = @"HomePhone2";

NSString *const HEWSPhoneNumberKeyType_ISDN = @"Isdn";

NSString *const HEWSPhoneNumberKeyType_MOBILE_PHONE = @"MobilePhone";

NSString *const HEWSPhoneNumberKeyType_OTHER_FAX = @"OtherFax";

NSString *const HEWSPhoneNumberKeyType_OTHER_TELEPHONE = @"OtherTelephone";

NSString *const HEWSPhoneNumberKeyType_PAGER = @"Pager";

NSString *const HEWSPhoneNumberKeyType_PRIMARY_PHONE = @"PrimaryPhone";

NSString *const HEWSPhoneNumberKeyType_RADIO_PHONE = @"RadioPhone";

NSString *const HEWSPhoneNumberKeyType_TELEX = @"Telex";

NSString *const HEWSPhoneNumberKeyType_TTY_TDD_PHONE = @"TtyTddPhone";
