// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"



/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSArrayOfBinaryType : NSObject <PicoBindable> {

@private
    NSMutableArray *_base64Binary;

}


/**
 (public property)
 
 entry type : NSData, wrapper for primitive data
*/

@property (nonatomic, retain) NSMutableArray *base64Binary;


@end
