// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSDelegatePermissionsType.h"

@implementation HEWSDelegatePermissionsType

@synthesize calendarFolderPermissionLevel = _calendarFolderPermissionLevel;
@synthesize tasksFolderPermissionLevel = _tasksFolderPermissionLevel;
@synthesize inboxFolderPermissionLevel = _inboxFolderPermissionLevel;
@synthesize contactsFolderPermissionLevel = _contactsFolderPermissionLevel;
@synthesize notesFolderPermissionLevel = _notesFolderPermissionLevel;
@synthesize journalFolderPermissionLevel = _journalFolderPermissionLevel;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"CalendarFolderPermissionLevel" propertyName:@"calendarFolderPermissionLevel" type:PICO_TYPE_ENUM clazz:nil];
    [map setObject:ps forKey:@"calendarFolderPermissionLevel"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"TasksFolderPermissionLevel" propertyName:@"tasksFolderPermissionLevel" type:PICO_TYPE_ENUM clazz:nil];
    [map setObject:ps forKey:@"tasksFolderPermissionLevel"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"InboxFolderPermissionLevel" propertyName:@"inboxFolderPermissionLevel" type:PICO_TYPE_ENUM clazz:nil];
    [map setObject:ps forKey:@"inboxFolderPermissionLevel"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ContactsFolderPermissionLevel" propertyName:@"contactsFolderPermissionLevel" type:PICO_TYPE_ENUM clazz:nil];
    [map setObject:ps forKey:@"contactsFolderPermissionLevel"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"NotesFolderPermissionLevel" propertyName:@"notesFolderPermissionLevel" type:PICO_TYPE_ENUM clazz:nil];
    [map setObject:ps forKey:@"notesFolderPermissionLevel"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"JournalFolderPermissionLevel" propertyName:@"journalFolderPermissionLevel" type:PICO_TYPE_ENUM clazz:nil];
    [map setObject:ps forKey:@"journalFolderPermissionLevel"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.calendarFolderPermissionLevel = nil;
    self.tasksFolderPermissionLevel = nil;
    self.inboxFolderPermissionLevel = nil;
    self.contactsFolderPermissionLevel = nil;
    self.notesFolderPermissionLevel = nil;
    self.journalFolderPermissionLevel = nil;
    [super dealloc];
}

@end
