// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSSmtpDomain.h"

@implementation HEWSSmtpDomain

@synthesize name = _name;
@synthesize includeSubdomains = _includeSubdomains;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ATTRIBUTE xmlName:@"Name" propertyName:@"name" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"name"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ATTRIBUTE xmlName:@"IncludeSubdomains" propertyName:@"includeSubdomains" type:PICO_TYPE_BOOL clazz:nil];
    [map setObject:ps forKey:@"includeSubdomains"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.name = nil;
    self.includeSubdomains = nil;
    [super dealloc];
}

@end
