// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSRuleActionsType.h"
#import "HEWSArrayOfStringsType.h"
#import "HEWSItemIdType.h"
#import "HEWSArrayOfEmailAddressesType.h"
#import "HEWSTargetFolderIdType.h"

@implementation HEWSRuleActionsType

@synthesize assignCategories = _assignCategories;
@synthesize copyToFolder = _copyToFolder;
@synthesize delete = _delete;
@synthesize forwardAsAttachmentToRecipients = _forwardAsAttachmentToRecipients;
@synthesize forwardToRecipients = _forwardToRecipients;
@synthesize markImportance = _markImportance;
@synthesize markAsRead = _markAsRead;
@synthesize moveToFolder = _moveToFolder;
@synthesize permanentDelete = _permanentDelete;
@synthesize redirectToRecipients = _redirectToRecipients;
@synthesize sendSMSAlertToRecipients = _sendSMSAlertToRecipients;
@synthesize serverReplyWithMessage = _serverReplyWithMessage;
@synthesize stopProcessingRules = _stopProcessingRules;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"AssignCategories" propertyName:@"assignCategories" type:PICO_TYPE_OBJECT clazz:[HEWSArrayOfStringsType class]];
    [map setObject:ps forKey:@"assignCategories"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"CopyToFolder" propertyName:@"copyToFolder" type:PICO_TYPE_OBJECT clazz:[HEWSTargetFolderIdType class]];
    [map setObject:ps forKey:@"copyToFolder"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Delete" propertyName:@"delete" type:PICO_TYPE_BOOL clazz:nil];
    [map setObject:ps forKey:@"delete"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ForwardAsAttachmentToRecipients" propertyName:@"forwardAsAttachmentToRecipients" type:PICO_TYPE_OBJECT clazz:[HEWSArrayOfEmailAddressesType class]];
    [map setObject:ps forKey:@"forwardAsAttachmentToRecipients"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ForwardToRecipients" propertyName:@"forwardToRecipients" type:PICO_TYPE_OBJECT clazz:[HEWSArrayOfEmailAddressesType class]];
    [map setObject:ps forKey:@"forwardToRecipients"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"MarkImportance" propertyName:@"markImportance" type:PICO_TYPE_ENUM clazz:nil];
    [map setObject:ps forKey:@"markImportance"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"MarkAsRead" propertyName:@"markAsRead" type:PICO_TYPE_BOOL clazz:nil];
    [map setObject:ps forKey:@"markAsRead"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"MoveToFolder" propertyName:@"moveToFolder" type:PICO_TYPE_OBJECT clazz:[HEWSTargetFolderIdType class]];
    [map setObject:ps forKey:@"moveToFolder"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"PermanentDelete" propertyName:@"permanentDelete" type:PICO_TYPE_BOOL clazz:nil];
    [map setObject:ps forKey:@"permanentDelete"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"RedirectToRecipients" propertyName:@"redirectToRecipients" type:PICO_TYPE_OBJECT clazz:[HEWSArrayOfEmailAddressesType class]];
    [map setObject:ps forKey:@"redirectToRecipients"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"SendSMSAlertToRecipients" propertyName:@"sendSMSAlertToRecipients" type:PICO_TYPE_OBJECT clazz:[HEWSArrayOfEmailAddressesType class]];
    [map setObject:ps forKey:@"sendSMSAlertToRecipients"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ServerReplyWithMessage" propertyName:@"serverReplyWithMessage" type:PICO_TYPE_OBJECT clazz:[HEWSItemIdType class]];
    [map setObject:ps forKey:@"serverReplyWithMessage"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"StopProcessingRules" propertyName:@"stopProcessingRules" type:PICO_TYPE_BOOL clazz:nil];
    [map setObject:ps forKey:@"stopProcessingRules"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.assignCategories = nil;
    self.copyToFolder = nil;
    self.delete = nil;
    self.forwardAsAttachmentToRecipients = nil;
    self.forwardToRecipients = nil;
    self.markImportance = nil;
    self.markAsRead = nil;
    self.moveToFolder = nil;
    self.permanentDelete = nil;
    self.redirectToRecipients = nil;
    self.sendSMSAlertToRecipients = nil;
    self.serverReplyWithMessage = nil;
    self.stopProcessingRules = nil;
    [super dealloc];
}

@end
