// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import "HEWSSortDirectionType.h"


NSString *const HEWSSortDirectionType_ASCENDING = @"Ascending";

NSString *const HEWSSortDirectionType_DESCENDING = @"Descending";
