// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class HEWSUserIdType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSArrayOfUserIdType : NSObject <PicoBindable> {

@private
    NSMutableArray *_userId;

}


/**
 (public property)
 
 entry type : class HEWSUserIdType
*/

@property (nonatomic, retain) NSMutableArray *userId;


@end
