// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSSuggestionsViewOptionsType.h"
#import "HEWSDuration.h"

@implementation HEWSSuggestionsViewOptionsType

@synthesize goodThreshold = _goodThreshold;
@synthesize maximumResultsByDay = _maximumResultsByDay;
@synthesize maximumNonWorkHourResultsByDay = _maximumNonWorkHourResultsByDay;
@synthesize meetingDurationInMinutes = _meetingDurationInMinutes;
@synthesize minimumSuggestionQuality = _minimumSuggestionQuality;
@synthesize detailedSuggestionsWindow = _detailedSuggestionsWindow;
@synthesize currentMeetingTime = _currentMeetingTime;
@synthesize globalObjectId = _globalObjectId;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    PicoClassSchema *cs = [[PicoClassSchema alloc] initWithXmlName:@"SuggestionsViewOptions" nsUri:@"http://schemas.microsoft.com/exchange/services/2006/types"];
    [cs autorelease];
    return cs;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"GoodThreshold" propertyName:@"goodThreshold" type:PICO_TYPE_INT clazz:nil];
    [map setObject:ps forKey:@"goodThreshold"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"MaximumResultsByDay" propertyName:@"maximumResultsByDay" type:PICO_TYPE_INT clazz:nil];
    [map setObject:ps forKey:@"maximumResultsByDay"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"MaximumNonWorkHourResultsByDay" propertyName:@"maximumNonWorkHourResultsByDay" type:PICO_TYPE_INT clazz:nil];
    [map setObject:ps forKey:@"maximumNonWorkHourResultsByDay"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"MeetingDurationInMinutes" propertyName:@"meetingDurationInMinutes" type:PICO_TYPE_INT clazz:nil];
    [map setObject:ps forKey:@"meetingDurationInMinutes"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"MinimumSuggestionQuality" propertyName:@"minimumSuggestionQuality" type:PICO_TYPE_ENUM clazz:nil];
    [map setObject:ps forKey:@"minimumSuggestionQuality"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"DetailedSuggestionsWindow" propertyName:@"detailedSuggestionsWindow" type:PICO_TYPE_OBJECT clazz:[HEWSDuration class]];
    [map setObject:ps forKey:@"detailedSuggestionsWindow"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"CurrentMeetingTime" propertyName:@"currentMeetingTime" type:PICO_TYPE_DATE clazz:nil];
    [map setObject:ps forKey:@"currentMeetingTime"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"GlobalObjectId" propertyName:@"globalObjectId" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"globalObjectId"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.goodThreshold = nil;
    self.maximumResultsByDay = nil;
    self.maximumNonWorkHourResultsByDay = nil;
    self.meetingDurationInMinutes = nil;
    self.minimumSuggestionQuality = nil;
    self.detailedSuggestionsWindow = nil;
    self.currentMeetingTime = nil;
    self.globalObjectId = nil;
    [super dealloc];
}

@end
