// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import "HEWSDeliverMeetingRequestsType.h"


NSString *const HEWSDeliverMeetingRequestsType_DELEGATES_ONLY = @"DelegatesOnly";

NSString *const HEWSDeliverMeetingRequestsType_DELEGATES_AND_ME = @"DelegatesAndMe";

NSString *const HEWSDeliverMeetingRequestsType_DELEGATES_AND_SEND_INFORMATION_TO_ME = @"DelegatesAndSendInformationToMe";

NSString *const HEWSDeliverMeetingRequestsType_NO_FORWARD = @"NoForward";
