// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class HEWSInvalidRecipientType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSArrayOfInvalidRecipientsType : NSObject <PicoBindable> {

@private
    NSMutableArray *_invalidRecipient;

}


/**
 (public property)
 
 entry type : class HEWSInvalidRecipientType
*/

@property (nonatomic, retain) NSMutableArray *invalidRecipient;


@end
