// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import "HEWSCalendarPermissionReadAccessType.h"


NSString *const HEWSCalendarPermissionReadAccessType_NONE = @"None";

NSString *const HEWSCalendarPermissionReadAccessType_TIME_ONLY = @"TimeOnly";

NSString *const HEWSCalendarPermissionReadAccessType_TIME_AND_SUBJECT_AND_LOCATION = @"TimeAndSubjectAndLocation";

NSString *const HEWSCalendarPermissionReadAccessType_FULL_DETAILS = @"FullDetails";
