// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import "HEWSResponseTypeType.h"


NSString *const HEWSResponseTypeType_UNKNOWN = @"Unknown";

NSString *const HEWSResponseTypeType_ORGANIZER = @"Organizer";

NSString *const HEWSResponseTypeType_TENTATIVE = @"Tentative";

NSString *const HEWSResponseTypeType_ACCEPT = @"Accept";

NSString *const HEWSResponseTypeType_DECLINE = @"Decline";

NSString *const HEWSResponseTypeType_NO_RESPONSE_RECEIVED = @"NoResponseReceived";
