// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class HEWSProtectionRuleType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSArrayOfProtectionRulesType : NSObject <PicoBindable> {

@private
    NSMutableArray *_rule;

}


/**
 (public property)
 
 entry type : class HEWSProtectionRuleType
*/

@property (nonatomic, retain) NSMutableArray *rule;


@end
