// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSMailTips.h"
#import "HEWSOutOfOfficeMailTip.h"
#import "HEWSEmailAddressType.h"

@implementation HEWSMailTips

@synthesize recipientAddress = _recipientAddress;
@synthesize pendingMailTips = _pendingMailTips;
@synthesize outOfOffice = _outOfOffice;
@synthesize mailboxFull = _mailboxFull;
@synthesize customMailTip = _customMailTip;
@synthesize totalMemberCount = _totalMemberCount;
@synthesize externalMemberCount = _externalMemberCount;
@synthesize maxMessageSize = _maxMessageSize;
@synthesize deliveryRestricted = _deliveryRestricted;
@synthesize isModerated = _isModerated;
@synthesize invalidRecipient = _invalidRecipient;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"RecipientAddress" propertyName:@"recipientAddress" type:PICO_TYPE_OBJECT clazz:[HEWSEmailAddressType class]];
    [map setObject:ps forKey:@"recipientAddress"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"PendingMailTips" propertyName:@"pendingMailTips" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"pendingMailTips"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"OutOfOffice" propertyName:@"outOfOffice" type:PICO_TYPE_OBJECT clazz:[HEWSOutOfOfficeMailTip class]];
    [map setObject:ps forKey:@"outOfOffice"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"MailboxFull" propertyName:@"mailboxFull" type:PICO_TYPE_BOOL clazz:nil];
    [map setObject:ps forKey:@"mailboxFull"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"CustomMailTip" propertyName:@"customMailTip" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"customMailTip"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"TotalMemberCount" propertyName:@"totalMemberCount" type:PICO_TYPE_INT clazz:nil];
    [map setObject:ps forKey:@"totalMemberCount"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ExternalMemberCount" propertyName:@"externalMemberCount" type:PICO_TYPE_INT clazz:nil];
    [map setObject:ps forKey:@"externalMemberCount"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"MaxMessageSize" propertyName:@"maxMessageSize" type:PICO_TYPE_INT clazz:nil];
    [map setObject:ps forKey:@"maxMessageSize"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"DeliveryRestricted" propertyName:@"deliveryRestricted" type:PICO_TYPE_BOOL clazz:nil];
    [map setObject:ps forKey:@"deliveryRestricted"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"IsModerated" propertyName:@"isModerated" type:PICO_TYPE_BOOL clazz:nil];
    [map setObject:ps forKey:@"isModerated"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"InvalidRecipient" propertyName:@"invalidRecipient" type:PICO_TYPE_BOOL clazz:nil];
    [map setObject:ps forKey:@"invalidRecipient"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.recipientAddress = nil;
    self.pendingMailTips = nil;
    self.outOfOffice = nil;
    self.mailboxFull = nil;
    self.customMailTip = nil;
    self.totalMemberCount = nil;
    self.externalMemberCount = nil;
    self.maxMessageSize = nil;
    self.deliveryRestricted = nil;
    self.isModerated = nil;
    self.invalidRecipient = nil;
    [super dealloc];
}

@end
