// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSArrayOfCalendarEvent.h"
#import "HEWSCalendarEvent.h"

@implementation HEWSArrayOfCalendarEvent

@synthesize calendarEvent = _calendarEvent;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"CalendarEvent" propertyName:@"calendarEvent" type:PICO_TYPE_OBJECT clazz:[HEWSCalendarEvent class]];
    [map setObject:ps forKey:@"calendarEvent"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.calendarEvent = nil;
    [super dealloc];
}

@end
