// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import "HEWSContainmentComparisonType.h"


NSString *const HEWSContainmentComparisonType_EXACT = @"Exact";

NSString *const HEWSContainmentComparisonType_IGNORE_CASE = @"IgnoreCase";

NSString *const HEWSContainmentComparisonType_IGNORE_NON_SPACING_CHARACTERS = @"IgnoreNonSpacingCharacters";

NSString *const HEWSContainmentComparisonType_LOOSE = @"Loose";

NSString *const HEWSContainmentComparisonType_IGNORE_CASE_AND_NON_SPACING_CHARACTERS = @"IgnoreCaseAndNonSpacingCharacters";

NSString *const HEWSContainmentComparisonType_LOOSE_AND_IGNORE_CASE = @"LooseAndIgnoreCase";

NSString *const HEWSContainmentComparisonType_LOOSE_AND_IGNORE_NON_SPACE = @"LooseAndIgnoreNonSpace";

NSString *const HEWSContainmentComparisonType_LOOSE_AND_IGNORE_CASE_AND_IGNORE_NON_SPACE = @"LooseAndIgnoreCaseAndIgnoreNonSpace";
