// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>

/**
 @file
 
         Defines the well known property set ids for extended properties.
       
 
 @ingroup ExchangeServicePortType
*/

extern NSString *const HEWSDistinguishedPropertySetType_MEETING;

extern NSString *const HEWSDistinguishedPropertySetType_APPOINTMENT;

extern NSString *const HEWSDistinguishedPropertySetType_COMMON;

extern NSString *const HEWSDistinguishedPropertySetType_PUBLIC_STRINGS;

extern NSString *const HEWSDistinguishedPropertySetType_ADDRESS;

extern NSString *const HEWSDistinguishedPropertySetType_INTERNET_HEADERS;

extern NSString *const HEWSDistinguishedPropertySetType_CALENDAR_ASSISTANT;

extern NSString *const HEWSDistinguishedPropertySetType_UNIFIED_MESSAGING;

extern NSString *const HEWSDistinguishedPropertySetType_TASK;
