// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSNonEmptyArrayOfOccurrenceInfoType.h"
#import "HEWSOccurrenceInfoType.h"

@implementation HEWSNonEmptyArrayOfOccurrenceInfoType

@synthesize occurrence = _occurrence;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"Occurrence" propertyName:@"occurrence" type:PICO_TYPE_OBJECT clazz:[HEWSOccurrenceInfoType class]];
    [map setObject:ps forKey:@"occurrence"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.occurrence = nil;
    [super dealloc];
}

@end
