// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "HEWSAttachmentType.h"



/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSFileAttachmentType : HEWSAttachmentType {

@private
    NSNumber *_isContactPhoto;
    NSData *_content;

}


/**
 (public property)
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *isContactPhoto;

/**
 (public property)
 
 type : NSData, wrapper for primitive data
*/
@property (nonatomic, retain) NSData *content;


@end
