// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>


extern NSString *const HEWSFileAsMappingType_NONE;

extern NSString *const HEWSFileAsMappingType_LAST_COMMA_FIRST;

extern NSString *const HEWSFileAsMappingType_FIRST_SPACE_LAST;

extern NSString *const HEWSFileAsMappingType_COMPANY;

extern NSString *const HEWSFileAsMappingType_LAST_COMMA_FIRST_COMPANY;

extern NSString *const HEWSFileAsMappingType_COMPANY_LAST_FIRST;

extern NSString *const HEWSFileAsMappingType_LAST_FIRST;

extern NSString *const HEWSFileAsMappingType_LAST_FIRST_COMPANY;

extern NSString *const HEWSFileAsMappingType_COMPANY_LAST_COMMA_FIRST;

extern NSString *const HEWSFileAsMappingType_LAST_FIRST_SUFFIX;

extern NSString *const HEWSFileAsMappingType_LAST_SPACE_FIRST_COMPANY;

extern NSString *const HEWSFileAsMappingType_COMPANY_LAST_SPACE_FIRST;

extern NSString *const HEWSFileAsMappingType_LAST_SPACE_FIRST;

extern NSString *const HEWSFileAsMappingType_DISPLAY_NAME;

extern NSString *const HEWSFileAsMappingType_FIRST_NAME;

extern NSString *const HEWSFileAsMappingType_LAST_FIRST_MIDDLE_SUFFIX;

extern NSString *const HEWSFileAsMappingType_LAST_NAME;

extern NSString *const HEWSFileAsMappingType_EMPTY;
