// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSNonEmptyArrayOfPathsToElementType.h"

@implementation HEWSNonEmptyArrayOfPathsToElementType

@synthesize path = _path;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ANY_ELEMENT xmlName:@"path" propertyName:@"path" type:PICO_TYPE_OBJECT clazz:[HEWSJAXBElement<? extends BasePathToElementType> class]];
    [map setObject:ps forKey:@"path"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.path = nil;
    [super dealloc];
}

@end
