// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSArrayOfEncryptedSharedFolderDataType.h"
#import "HEWSEncryptedSharedFolderDataType.h"

@implementation HEWSArrayOfEncryptedSharedFolderDataType

@synthesize encryptedSharedFolderData = _encryptedSharedFolderData;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"EncryptedSharedFolderData" propertyName:@"encryptedSharedFolderData" type:PICO_TYPE_OBJECT clazz:[HEWSEncryptedSharedFolderDataType class]];
    [map setObject:ps forKey:@"encryptedSharedFolderData"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.encryptedSharedFolderData = nil;
    [super dealloc];
}

@end
