// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import "HEWSAffectedTaskOccurrencesType.h"


NSString *const HEWSAffectedTaskOccurrencesType_ALL_OCCURRENCES = @"AllOccurrences";

NSString *const HEWSAffectedTaskOccurrencesType_SPECIFIED_OCCURRENCE_ONLY = @"SpecifiedOccurrenceOnly";
