// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class HEWSPathToExtendedFieldType;
@class HEWSNonEmptyArrayOfPropertyValuesType;

/**
 
         Represents an extended property instance (both its path identifier along with its
         associated value).
       
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSExtendedPropertyType : NSObject <PicoBindable> {

@private
    HEWSPathToExtendedFieldType *_extendedFieldURI;
    NSString *_value;
    HEWSNonEmptyArrayOfPropertyValuesType *_values;

}


/**
 (public property)
 
 type : class HEWSPathToExtendedFieldType
*/
@property (nonatomic, retain) HEWSPathToExtendedFieldType *extendedFieldURI;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *value;

/**
 (public property)
 
 type : class HEWSNonEmptyArrayOfPropertyValuesType
*/
@property (nonatomic, retain) HEWSNonEmptyArrayOfPropertyValuesType *values;


@end
