// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSRecurringMasterItemIdType.h"

@implementation HEWSRecurringMasterItemIdType

@synthesize occurrenceId = _occurrenceId;
@synthesize changeKey = _changeKey;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ATTRIBUTE xmlName:@"OccurrenceId" propertyName:@"occurrenceId" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"occurrenceId"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ATTRIBUTE xmlName:@"ChangeKey" propertyName:@"changeKey" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"changeKey"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.occurrenceId = nil;
    self.changeKey = nil;
    [super dealloc];
}

@end
