// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>


extern NSString *const HEWSTaskStatusType_NOT_STARTED;

extern NSString *const HEWSTaskStatusType_IN_PROGRESS;

extern NSString *const HEWSTaskStatusType_COMPLETED;

extern NSString *const HEWSTaskStatusType_WAITING_ON_OTHERS;

extern NSString *const HEWSTaskStatusType_DEFERRED;
