// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class HEWSNonEmptyArrayOfRestrictedGroupIdentifiersType;
@class HEWSNonEmptyArrayOfGroupIdentifiersType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSSerializedSecurityContextType : NSObject <PicoBindable> {

@private
    NSString *_userSid;
    HEWSNonEmptyArrayOfGroupIdentifiersType *_groupSids;
    HEWSNonEmptyArrayOfRestrictedGroupIdentifiersType *_restrictedGroupSids;
    NSString *_primarySmtpAddress;

}


/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *userSid;

/**
 (public property)
 
 type : class HEWSNonEmptyArrayOfGroupIdentifiersType
*/
@property (nonatomic, retain) HEWSNonEmptyArrayOfGroupIdentifiersType *groupSids;

/**
 (public property)
 
 type : class HEWSNonEmptyArrayOfRestrictedGroupIdentifiersType
*/
@property (nonatomic, retain) HEWSNonEmptyArrayOfRestrictedGroupIdentifiersType *restrictedGroupSids;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *primarySmtpAddress;


@end
