// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>


extern NSString *const HEWSExchangeVersionType_EXCHANGE_2007;

extern NSString *const HEWSExchangeVersionType_EXCHANGE_2007_SP_1;

extern NSString *const HEWSExchangeVersionType_EXCHANGE_2010;

extern NSString *const HEWSExchangeVersionType_EXCHANGE_2010_SP_1;

extern NSString *const HEWSExchangeVersionType_EXCHANGE_2010_SP_2;
