// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class HEWSInternetHeaderType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSNonEmptyArrayOfInternetHeadersType : NSObject <PicoBindable> {

@private
    NSMutableArray *_internetMessageHeader;

}


/**
 (public property)
 
 entry type : class HEWSInternetHeaderType
*/

@property (nonatomic, retain) NSMutableArray *internetMessageHeader;


@end
