// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import "HEWSConnectionStatusType.h"


NSString *const HEWSConnectionStatusType_OK = @"OK";

NSString *const HEWSConnectionStatusType_CLOSED = @"Closed";
