// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>


extern NSString *const HEWSExternalAudience_NONE;

extern NSString *const HEWSExternalAudience_KNOWN;

extern NSString *const HEWSExternalAudience_ALL;
