// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "HEWSServiceConfiguration.h"



/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSUnifiedMessageServiceConfiguration : HEWSServiceConfiguration {

@private
    NSNumber *_umEnabled;
    NSString *_playOnPhoneDialString;
    NSNumber *_playOnPhoneEnabled;

}


/**
 (public property)
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *umEnabled;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *playOnPhoneDialString;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *playOnPhoneEnabled;


@end
