// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class HEWSBaseFolderType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSNonEmptyArrayOfFoldersType : NSObject <PicoBindable> {

@private
    NSMutableArray *_folderOrCalendarFolderOrContactsFolder;

}


/**
 (public property)
 
 entry type : class HEWSBaseFolderType
*/

@property (nonatomic, retain) NSMutableArray *folderOrCalendarFolderOrContactsFolder;


@end
