// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class HEWSUserConfigurationDictionaryObjectType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSUserConfigurationDictionaryEntryType : NSObject <PicoBindable> {

@private
    HEWSUserConfigurationDictionaryObjectType *_dictionaryKey;
    HEWSUserConfigurationDictionaryObjectType *_dictionaryValue;

}


/**
 (public property)
 
 type : class HEWSUserConfigurationDictionaryObjectType
*/
@property (nonatomic, retain) HEWSUserConfigurationDictionaryObjectType *dictionaryKey;

/**
 (public property)
 
 type : class HEWSUserConfigurationDictionaryObjectType
*/
@property (nonatomic, retain) HEWSUserConfigurationDictionaryObjectType *dictionaryValue;


@end
