// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"



/**
 
         Keyword statistics search result.
       
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSKeywordStatisticsSearchResultType : NSObject <PicoBindable> {

@private
    NSString *_keyword;
    NSNumber *_itemHits;
    NSNumber *_size;

}


/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *keyword;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *itemHits;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive long
*/
@property (nonatomic, retain) NSNumber *size;


@end
