// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class HEWSTimeZoneDefinitionType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSTimeZoneContextType : NSObject <PicoBindable> {

@private
    HEWSTimeZoneDefinitionType *_timeZoneDefinition;

}


/**
 (public property)
 
 type : class HEWSTimeZoneDefinitionType
*/
@property (nonatomic, retain) HEWSTimeZoneDefinitionType *timeZoneDefinition;


@end
