// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSMovedCopiedEventType.h"
#import "HEWSItemIdType.h"
#import "HEWSFolderIdType.h"

@implementation HEWSMovedCopiedEventType

@synthesize oldFolderId = _oldFolderId;
@synthesize oldItemId = _oldItemId;
@synthesize oldParentFolderId = _oldParentFolderId;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    PicoClassSchema *cs = [[PicoClassSchema alloc] initWithXmlName:@"MovedEvent" nsUri:@"http://schemas.microsoft.com/exchange/services/2006/types"];
    [cs autorelease];
    return cs;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"OldFolderId" propertyName:@"oldFolderId" type:PICO_TYPE_OBJECT clazz:[HEWSFolderIdType class]];
    [map setObject:ps forKey:@"oldFolderId"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"OldItemId" propertyName:@"oldItemId" type:PICO_TYPE_OBJECT clazz:[HEWSItemIdType class]];
    [map setObject:ps forKey:@"oldItemId"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"OldParentFolderId" propertyName:@"oldParentFolderId" type:PICO_TYPE_OBJECT clazz:[HEWSFolderIdType class]];
    [map setObject:ps forKey:@"oldParentFolderId"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.oldFolderId = nil;
    self.oldItemId = nil;
    self.oldParentFolderId = nil;
    [super dealloc];
}

@end
