// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>


extern NSString *const HEWSDistinguishedUserType_DEFAULT;

extern NSString *const HEWSDistinguishedUserType_ANONYMOUS;
