// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class HEWSNonEmptyArrayOfResponseObjectsType;
@class HEWSArrayOfStringsType;
@class HEWSBodyType;
@class HEWSEffectiveRightsType;
@class HEWSMimeContentType;
@class HEWSItemIdType;
@class HEWSFolderIdType;
@class HEWSExtendedPropertyType;
@class HEWSNonEmptyArrayOfInternetHeadersType;
@class HEWSNonEmptyArrayOfAttachmentsType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSItemType : NSObject <PicoBindable> {

@private
    HEWSMimeContentType *_mimeContent;
    HEWSItemIdType *_itemId;
    HEWSFolderIdType *_parentFolderId;
    NSString *_itemClass;
    NSString *_subject;
    NSString *_sensitivity;
    HEWSBodyType *_body;
    HEWSNonEmptyArrayOfAttachmentsType *_attachments;
    NSDate *_dateTimeReceived;
    NSNumber *_size;
    HEWSArrayOfStringsType *_categories;
    NSString *_importance;
    NSString *_inReplyTo;
    NSNumber *_isSubmitted;
    NSNumber *_isDraft;
    NSNumber *_isFromMe;
    NSNumber *_isResend;
    NSNumber *_isUnmodified;
    HEWSNonEmptyArrayOfInternetHeadersType *_internetMessageHeaders;
    NSDate *_dateTimeSent;
    NSDate *_dateTimeCreated;
    HEWSNonEmptyArrayOfResponseObjectsType *_responseObjects;
    NSDate *_reminderDueBy;
    NSNumber *_reminderIsSet;
    NSString *_reminderMinutesBeforeStart;
    NSString *_displayCc;
    NSString *_displayTo;
    NSNumber *_hasAttachments;
    NSMutableArray *_extendedProperty;
    NSString *_culture;
    HEWSEffectiveRightsType *_effectiveRights;
    NSString *_lastModifiedName;
    NSDate *_lastModifiedTime;
    NSNumber *_isAssociated;
    NSString *_webClientReadFormQueryString;
    NSString *_webClientEditFormQueryString;
    HEWSItemIdType *_conversationId;
    HEWSBodyType *_uniqueBody;
    NSData *_storeEntryId;

}


/**
 (public property)
 
 type : class HEWSMimeContentType
*/
@property (nonatomic, retain) HEWSMimeContentType *mimeContent;

/**
 (public property)
 
 type : class HEWSItemIdType
*/
@property (nonatomic, retain) HEWSItemIdType *itemId;

/**
 (public property)
 
 type : class HEWSFolderIdType
*/
@property (nonatomic, retain) HEWSFolderIdType *parentFolderId;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *itemClass;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *subject;

/**
 (public property)
 
 type: string constant in HEWSSensitivityChoicesType.h
*/
@property (nonatomic, retain) NSString *sensitivity;

/**
 (public property)
 
 type : class HEWSBodyType
*/
@property (nonatomic, retain) HEWSBodyType *body;

/**
 (public property)
 
 type : class HEWSNonEmptyArrayOfAttachmentsType
*/
@property (nonatomic, retain) HEWSNonEmptyArrayOfAttachmentsType *attachments;

/**
 (public property)
 
 type : NSDate, wrapper for primitive date
*/
@property (nonatomic, retain) NSDate *dateTimeReceived;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *size;

/**
 (public property)
 
 type : class HEWSArrayOfStringsType
*/
@property (nonatomic, retain) HEWSArrayOfStringsType *categories;

/**
 (public property)
 
 type: string constant in HEWSImportanceChoicesType.h
*/
@property (nonatomic, retain) NSString *importance;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *inReplyTo;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *isSubmitted;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *isDraft;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *isFromMe;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *isResend;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *isUnmodified;

/**
 (public property)
 
 type : class HEWSNonEmptyArrayOfInternetHeadersType
*/
@property (nonatomic, retain) HEWSNonEmptyArrayOfInternetHeadersType *internetMessageHeaders;

/**
 (public property)
 
 type : NSDate, wrapper for primitive date
*/
@property (nonatomic, retain) NSDate *dateTimeSent;

/**
 (public property)
 
 type : NSDate, wrapper for primitive date
*/
@property (nonatomic, retain) NSDate *dateTimeCreated;

/**
 (public property)
 
 type : class HEWSNonEmptyArrayOfResponseObjectsType
*/
@property (nonatomic, retain) HEWSNonEmptyArrayOfResponseObjectsType *responseObjects;

/**
 (public property)
 
 type : NSDate, wrapper for primitive date
*/
@property (nonatomic, retain) NSDate *reminderDueBy;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *reminderIsSet;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *reminderMinutesBeforeStart;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *displayCc;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *displayTo;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *hasAttachments;

/**
 (public property)
 
 entry type : class HEWSExtendedPropertyType
*/

@property (nonatomic, retain) NSMutableArray *extendedProperty;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *culture;

/**
 (public property)
 
 type : class HEWSEffectiveRightsType
*/
@property (nonatomic, retain) HEWSEffectiveRightsType *effectiveRights;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *lastModifiedName;

/**
 (public property)
 
 type : NSDate, wrapper for primitive date
*/
@property (nonatomic, retain) NSDate *lastModifiedTime;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *isAssociated;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *webClientReadFormQueryString;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *webClientEditFormQueryString;

/**
 (public property)
 
 type : class HEWSItemIdType
*/
@property (nonatomic, retain) HEWSItemIdType *conversationId;

/**
 (public property)
 
 type : class HEWSBodyType
*/
@property (nonatomic, retain) HEWSBodyType *uniqueBody;

/**
 (public property)
 
 type : NSData, wrapper for primitive data
*/
@property (nonatomic, retain) NSData *storeEntryId;


@end
