// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class HEWSConnectingSIDType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSExchangeImpersonationType : NSObject <PicoBindable> {

@private
    HEWSConnectingSIDType *_connectingSID;

}


/**
 (public property)
 
 type : class HEWSConnectingSIDType
*/
@property (nonatomic, retain) HEWSConnectingSIDType *connectingSID;


@end
