// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>

/**
 @file
 Type of conflict resolution to attempt during update
 
 @ingroup ExchangeServicePortType
*/

extern NSString *const HEWSConflictResolutionType_NEVER_OVERWRITE;

extern NSString *const HEWSConflictResolutionType_AUTO_RESOLVE;

extern NSString *const HEWSConflictResolutionType_ALWAYS_OVERWRITE;
