// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSFieldURIOrConstantType.h"
#import "HEWSJAXBElement<? extends BasePathToElementType>.h"
#import "HEWSConstantValueType.h"

@implementation HEWSFieldURIOrConstantType

@synthesize path = _path;
@synthesize constant = _constant;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ANY_ELEMENT xmlName:@"path" propertyName:@"path" type:PICO_TYPE_OBJECT clazz:[HEWSJAXBElement<? extends BasePathToElementType> class]];
    [map setObject:ps forKey:@"path"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Constant" propertyName:@"constant" type:PICO_TYPE_OBJECT clazz:[HEWSConstantValueType class]];
    [map setObject:ps forKey:@"constant"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.path = nil;
    self.constant = nil;
    [super dealloc];
}

@end
