// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class HEWSUserMailboxType;

/**
 
         Array of user mailbox.
       
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSArrayOfUserMailboxesType : NSObject <PicoBindable> {

@private
    NSMutableArray *_userMailbox;

}


/**
 (public property)
 
 entry type : class HEWSUserMailboxType
*/

@property (nonatomic, retain) NSMutableArray *userMailbox;


@end
