// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"



/**
 Date range type used for the WithinDateRange rule predicate.
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSRulePredicateDateRangeType : NSObject <PicoBindable> {

@private
    NSDate *_startDateTime;
    NSDate *_endDateTime;

}


/**
 (public property)
 
 type : NSDate, wrapper for primitive date
*/
@property (nonatomic, retain) NSDate *startDateTime;

/**
 (public property)
 
 type : NSDate, wrapper for primitive date
*/
@property (nonatomic, retain) NSDate *endDateTime;


@end
