// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSArrayOfSuggestionDayResult.h"
#import "HEWSSuggestionDayResult.h"

@implementation HEWSArrayOfSuggestionDayResult

@synthesize suggestionDayResult = _suggestionDayResult;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"SuggestionDayResult" propertyName:@"suggestionDayResult" type:PICO_TYPE_OBJECT clazz:[HEWSSuggestionDayResult class]];
    [map setObject:ps forKey:@"suggestionDayResult"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.suggestionDayResult = nil;
    [super dealloc];
}

@end
