// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>


extern NSString *const HEWSSensitivityChoicesType_NORMAL;

extern NSString *const HEWSSensitivityChoicesType_PERSONAL;

extern NSString *const HEWSSensitivityChoicesType_PRIVATE;

extern NSString *const HEWSSensitivityChoicesType_CONFIDENTIAL;
