// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSArrayOfAttendeeConflictData.h"
#import "HEWSAttendeeConflictData.h"

@implementation HEWSArrayOfAttendeeConflictData

@synthesize unknownAttendeeConflictDataOrIndividualAttendeeConflictDataOrTooBigGroupAttendeeConflictData = _unknownAttendeeConflictDataOrIndividualAttendeeConflictDataOrTooBigGroupAttendeeConflictData;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"unknownAttendeeConflictDataOrIndividualAttendeeConflictDataOrTooBigGroupAttendeeConflictData" propertyName:@"unknownAttendeeConflictDataOrIndividualAttendeeConflictDataOrTooBigGroupAttendeeConflictData" type:PICO_TYPE_OBJECT clazz:[HEWSAttendeeConflictData class]];
    [map setObject:ps forKey:@"unknownAttendeeConflictDataOrIndividualAttendeeConflictDataOrTooBigGroupAttendeeConflictData"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.unknownAttendeeConflictDataOrIndividualAttendeeConflictDataOrTooBigGroupAttendeeConflictData = nil;
    [super dealloc];
}

@end
