// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSGroupAttendeeConflictData.h"

@implementation HEWSGroupAttendeeConflictData

@synthesize numberOfMembers = _numberOfMembers;
@synthesize numberOfMembersAvailable = _numberOfMembersAvailable;
@synthesize numberOfMembersWithConflict = _numberOfMembersWithConflict;
@synthesize numberOfMembersWithNoData = _numberOfMembersWithNoData;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"NumberOfMembers" propertyName:@"numberOfMembers" type:PICO_TYPE_INT clazz:nil];
    [map setObject:ps forKey:@"numberOfMembers"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"NumberOfMembersAvailable" propertyName:@"numberOfMembersAvailable" type:PICO_TYPE_INT clazz:nil];
    [map setObject:ps forKey:@"numberOfMembersAvailable"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"NumberOfMembersWithConflict" propertyName:@"numberOfMembersWithConflict" type:PICO_TYPE_INT clazz:nil];
    [map setObject:ps forKey:@"numberOfMembersWithConflict"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"NumberOfMembersWithNoData" propertyName:@"numberOfMembersWithNoData" type:PICO_TYPE_INT clazz:nil];
    [map setObject:ps forKey:@"numberOfMembersWithNoData"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.numberOfMembers = nil;
    self.numberOfMembersAvailable = nil;
    self.numberOfMembersWithConflict = nil;
    self.numberOfMembersWithNoData = nil;
    [super dealloc];
}

@end
