// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSUserConfigurationType.h"
#import "HEWSUserConfigurationDictionaryType.h"
#import "HEWSItemIdType.h"
#import "HEWSUserConfigurationNameType.h"

@implementation HEWSUserConfigurationType

@synthesize userConfigurationName = _userConfigurationName;
@synthesize itemId = _itemId;
@synthesize dictionary = _dictionary;
@synthesize xmlData = _xmlData;
@synthesize binaryData = _binaryData;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"UserConfigurationName" propertyName:@"userConfigurationName" type:PICO_TYPE_OBJECT clazz:[HEWSUserConfigurationNameType class]];
    [map setObject:ps forKey:@"userConfigurationName"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ItemId" propertyName:@"itemId" type:PICO_TYPE_OBJECT clazz:[HEWSItemIdType class]];
    [map setObject:ps forKey:@"itemId"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Dictionary" propertyName:@"dictionary" type:PICO_TYPE_OBJECT clazz:[HEWSUserConfigurationDictionaryType class]];
    [map setObject:ps forKey:@"dictionary"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"XmlData" propertyName:@"xmlData" type:PICO_TYPE_DATA clazz:nil];
    [map setObject:ps forKey:@"xmlData"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"BinaryData" propertyName:@"binaryData" type:PICO_TYPE_DATA clazz:nil];
    [map setObject:ps forKey:@"binaryData"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.userConfigurationName = nil;
    self.itemId = nil;
    self.dictionary = nil;
    self.xmlData = nil;
    self.binaryData = nil;
    [super dealloc];
}

@end
