// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSDuration.h"

@implementation HEWSDuration

@synthesize startTime = _startTime;
@synthesize endTime = _endTime;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"StartTime" propertyName:@"startTime" type:PICO_TYPE_DATE clazz:nil];
    [map setObject:ps forKey:@"startTime"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"EndTime" propertyName:@"endTime" type:PICO_TYPE_DATE clazz:nil];
    [map setObject:ps forKey:@"endTime"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.startTime = nil;
    self.endTime = nil;
    [super dealloc];
}

@end
