// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import "HEWSFolderQueryTraversalType.h"

/**
 @file
 Types of sub-tree traversal for deletion and enumeration
*/

NSString *const HEWSFolderQueryTraversalType_SHALLOW = @"Shallow";

NSString *const HEWSFolderQueryTraversalType_DEEP = @"Deep";

NSString *const HEWSFolderQueryTraversalType_SOFT_DELETED = @"SoftDeleted";
