// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSDistributionListType.h"
#import "HEWSMembersListType.h"

@implementation HEWSDistributionListType

@synthesize displayName = _displayName;
@synthesize fileAs = _fileAs;
@synthesize contactSource = _contactSource;
@synthesize members = _members;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"DisplayName" propertyName:@"displayName" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"displayName"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"FileAs" propertyName:@"fileAs" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"fileAs"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ContactSource" propertyName:@"contactSource" type:PICO_TYPE_ENUM clazz:nil];
    [map setObject:ps forKey:@"contactSource"];
    [ps release];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Members" propertyName:@"members" type:PICO_TYPE_OBJECT clazz:[HEWSMembersListType class]];
    [map setObject:ps forKey:@"members"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.displayName = nil;
    self.fileAs = nil;
    self.contactSource = nil;
    self.members = nil;
    [super dealloc];
}

@end
