// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>

/**
 @file
 Rule field URI enumerates all possible rule fields that could trigger validation error
 
 @ingroup ExchangeServicePortType
*/

extern NSString *const HEWSRuleFieldURIType_RULE_ID;

extern NSString *const HEWSRuleFieldURIType_DISPLAY_NAME;

extern NSString *const HEWSRuleFieldURIType_PRIORITY;

extern NSString *const HEWSRuleFieldURIType_IS_NOT_SUPPORTED;

extern NSString *const HEWSRuleFieldURIType_ACTIONS;

extern NSString *const HEWSRuleFieldURIType_CONDITION_CATEGORIES;

extern NSString *const HEWSRuleFieldURIType_CONDITION_CONTAINS_BODY_STRINGS;

extern NSString *const HEWSRuleFieldURIType_CONDITION_CONTAINS_HEADER_STRINGS;

extern NSString *const HEWSRuleFieldURIType_CONDITION_CONTAINS_RECIPIENT_STRINGS;

extern NSString *const HEWSRuleFieldURIType_CONDITION_CONTAINS_SENDER_STRINGS;

extern NSString *const HEWSRuleFieldURIType_CONDITION_CONTAINS_SUBJECT_OR_BODY_STRINGS;

extern NSString *const HEWSRuleFieldURIType_CONDITION_CONTAINS_SUBJECT_STRINGS;

extern NSString *const HEWSRuleFieldURIType_CONDITION_FLAGGED_FOR_ACTION;

extern NSString *const HEWSRuleFieldURIType_CONDITION_FROM_ADDRESSES;

extern NSString *const HEWSRuleFieldURIType_CONDITION_FROM_CONNECTED_ACCOUNTS;

extern NSString *const HEWSRuleFieldURIType_CONDITION_HAS_ATTACHMENTS;

extern NSString *const HEWSRuleFieldURIType_CONDITION_IMPORTANCE;

extern NSString *const HEWSRuleFieldURIType_CONDITION_IS_APPROVAL_REQUEST;

extern NSString *const HEWSRuleFieldURIType_CONDITION_IS_AUTOMATIC_FORWARD;

extern NSString *const HEWSRuleFieldURIType_CONDITION_IS_AUTOMATIC_REPLY;

extern NSString *const HEWSRuleFieldURIType_CONDITION_IS_ENCRYPTED;

extern NSString *const HEWSRuleFieldURIType_CONDITION_IS_MEETING_REQUEST;

extern NSString *const HEWSRuleFieldURIType_CONDITION_IS_MEETING_RESPONSE;

extern NSString *const HEWSRuleFieldURIType_CONDITION_IS_NDR;

extern NSString *const HEWSRuleFieldURIType_CONDITION_IS_PERMISSION_CONTROLLED;

extern NSString *const HEWSRuleFieldURIType_CONDITION_IS_READ_RECEIPT;

extern NSString *const HEWSRuleFieldURIType_CONDITION_IS_SIGNED;

extern NSString *const HEWSRuleFieldURIType_CONDITION_IS_VOICEMAIL;

extern NSString *const HEWSRuleFieldURIType_CONDITION_ITEM_CLASSES;

extern NSString *const HEWSRuleFieldURIType_CONDITION_MESSAGE_CLASSIFICATIONS;

extern NSString *const HEWSRuleFieldURIType_CONDITION_NOT_SENT_TO_ME;

extern NSString *const HEWSRuleFieldURIType_CONDITION_SENT_CC_ME;

extern NSString *const HEWSRuleFieldURIType_CONDITION_SENT_ONLY_TO_ME;

extern NSString *const HEWSRuleFieldURIType_CONDITION_SENT_TO_ADDRESSES;

extern NSString *const HEWSRuleFieldURIType_CONDITION_SENT_TO_ME;

extern NSString *const HEWSRuleFieldURIType_CONDITION_SENT_TO_OR_CC_ME;

extern NSString *const HEWSRuleFieldURIType_CONDITION_SENSITIVITY;

extern NSString *const HEWSRuleFieldURIType_CONDITION_WITHIN_DATE_RANGE;

extern NSString *const HEWSRuleFieldURIType_CONDITION_WITHIN_SIZE_RANGE;

extern NSString *const HEWSRuleFieldURIType_EXCEPTION_CATEGORIES;

extern NSString *const HEWSRuleFieldURIType_EXCEPTION_CONTAINS_BODY_STRINGS;

extern NSString *const HEWSRuleFieldURIType_EXCEPTION_CONTAINS_HEADER_STRINGS;

extern NSString *const HEWSRuleFieldURIType_EXCEPTION_CONTAINS_RECIPIENT_STRINGS;

extern NSString *const HEWSRuleFieldURIType_EXCEPTION_CONTAINS_SENDER_STRINGS;

extern NSString *const HEWSRuleFieldURIType_EXCEPTION_CONTAINS_SUBJECT_OR_BODY_STRINGS;

extern NSString *const HEWSRuleFieldURIType_EXCEPTION_CONTAINS_SUBJECT_STRINGS;

extern NSString *const HEWSRuleFieldURIType_EXCEPTION_FLAGGED_FOR_ACTION;

extern NSString *const HEWSRuleFieldURIType_EXCEPTION_FROM_ADDRESSES;

extern NSString *const HEWSRuleFieldURIType_EXCEPTION_FROM_CONNECTED_ACCOUNTS;

extern NSString *const HEWSRuleFieldURIType_EXCEPTION_HAS_ATTACHMENTS;

extern NSString *const HEWSRuleFieldURIType_EXCEPTION_IMPORTANCE;

extern NSString *const HEWSRuleFieldURIType_EXCEPTION_IS_APPROVAL_REQUEST;

extern NSString *const HEWSRuleFieldURIType_EXCEPTION_IS_AUTOMATIC_FORWARD;

extern NSString *const HEWSRuleFieldURIType_EXCEPTION_IS_AUTOMATIC_REPLY;

extern NSString *const HEWSRuleFieldURIType_EXCEPTION_IS_ENCRYPTED;

extern NSString *const HEWSRuleFieldURIType_EXCEPTION_IS_MEETING_REQUEST;

extern NSString *const HEWSRuleFieldURIType_EXCEPTION_IS_MEETING_RESPONSE;

extern NSString *const HEWSRuleFieldURIType_EXCEPTION_IS_NDR;

extern NSString *const HEWSRuleFieldURIType_EXCEPTION_IS_PERMISSION_CONTROLLED;

extern NSString *const HEWSRuleFieldURIType_EXCEPTION_IS_READ_RECEIPT;

extern NSString *const HEWSRuleFieldURIType_EXCEPTION_IS_SIGNED;

extern NSString *const HEWSRuleFieldURIType_EXCEPTION_IS_VOICEMAIL;

extern NSString *const HEWSRuleFieldURIType_EXCEPTION_ITEM_CLASSES;

extern NSString *const HEWSRuleFieldURIType_EXCEPTION_MESSAGE_CLASSIFICATIONS;

extern NSString *const HEWSRuleFieldURIType_EXCEPTION_NOT_SENT_TO_ME;

extern NSString *const HEWSRuleFieldURIType_EXCEPTION_SENT_CC_ME;

extern NSString *const HEWSRuleFieldURIType_EXCEPTION_SENT_ONLY_TO_ME;

extern NSString *const HEWSRuleFieldURIType_EXCEPTION_SENT_TO_ADDRESSES;

extern NSString *const HEWSRuleFieldURIType_EXCEPTION_SENT_TO_ME;

extern NSString *const HEWSRuleFieldURIType_EXCEPTION_SENT_TO_OR_CC_ME;

extern NSString *const HEWSRuleFieldURIType_EXCEPTION_SENSITIVITY;

extern NSString *const HEWSRuleFieldURIType_EXCEPTION_WITHIN_DATE_RANGE;

extern NSString *const HEWSRuleFieldURIType_EXCEPTION_WITHIN_SIZE_RANGE;

extern NSString *const HEWSRuleFieldURIType_ACTION_ASSIGN_CATEGORIES;

extern NSString *const HEWSRuleFieldURIType_ACTION_COPY_TO_FOLDER;

extern NSString *const HEWSRuleFieldURIType_ACTION_DELETE;

extern NSString *const HEWSRuleFieldURIType_ACTION_FORWARD_AS_ATTACHMENT_TO_RECIPIENTS;

extern NSString *const HEWSRuleFieldURIType_ACTION_FORWARD_TO_RECIPIENTS;

extern NSString *const HEWSRuleFieldURIType_ACTION_MARK_IMPORTANCE;

extern NSString *const HEWSRuleFieldURIType_ACTION_MARK_AS_READ;

extern NSString *const HEWSRuleFieldURIType_ACTION_MOVE_TO_FOLDER;

extern NSString *const HEWSRuleFieldURIType_ACTION_PERMANENT_DELETE;

extern NSString *const HEWSRuleFieldURIType_ACTION_REDIRECT_TO_RECIPIENTS;

extern NSString *const HEWSRuleFieldURIType_ACTION_SEND_SMS_ALERT_TO_RECIPIENTS;

extern NSString *const HEWSRuleFieldURIType_ACTION_SERVER_REPLY_WITH_MESSAGE;

extern NSString *const HEWSRuleFieldURIType_ACTION_STOP_PROCESSING_RULES;

extern NSString *const HEWSRuleFieldURIType_IS_ENABLED;

extern NSString *const HEWSRuleFieldURIType_IS_IN_ERROR;

extern NSString *const HEWSRuleFieldURIType_CONDITIONS;

extern NSString *const HEWSRuleFieldURIType_EXCEPTIONS;
