// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>


extern NSString *const HEWSAvailabilityProxyRequestType_CROSS_SITE;

extern NSString *const HEWSAvailabilityProxyRequestType_CROSS_FOREST;
