// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import "HEWSInvalidRecipientResponseCodeType.h"

/**
 @file
 
         Represents the message keys that can be returned for invalid recipients
       
*/

NSString *const HEWSInvalidRecipientResponseCodeType_OTHER_ERROR = @"OtherError";

NSString *const HEWSInvalidRecipientResponseCodeType_RECIPIENT_ORGANIZATION_NOT_FEDERATED = @"RecipientOrganizationNotFederated";

NSString *const HEWSInvalidRecipientResponseCodeType_CANNOT_OBTAIN_TOKEN_FROM_STS = @"CannotObtainTokenFromSTS";

NSString *const HEWSInvalidRecipientResponseCodeType_SYSTEM_POLICY_BLOCKS_SHARING_WITH_THIS_RECIPIENT = @"SystemPolicyBlocksSharingWithThisRecipient";

NSString *const HEWSInvalidRecipientResponseCodeType_RECIPIENT_ORGANIZATION_FEDERATED_WITH_UNKNOWN_TOKEN_ISSUER = @"RecipientOrganizationFederatedWithUnknownTokenIssuer";
