// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSNonEmptyArrayOfFolderChangeDescriptionsType.h"
#import "HEWSFolderChangeDescriptionType.h"

@implementation HEWSNonEmptyArrayOfFolderChangeDescriptionsType

@synthesize appendToFolderFieldOrSetFolderFieldOrDeleteFolderField = _appendToFolderFieldOrSetFolderFieldOrDeleteFolderField;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"appendToFolderFieldOrSetFolderFieldOrDeleteFolderField" propertyName:@"appendToFolderFieldOrSetFolderFieldOrDeleteFolderField" type:PICO_TYPE_OBJECT clazz:[HEWSFolderChangeDescriptionType class]];
    [map setObject:ps forKey:@"appendToFolderFieldOrSetFolderFieldOrDeleteFolderField"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.appendToFolderFieldOrSetFolderFieldOrDeleteFolderField = nil;
    [super dealloc];
}

@end
