// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>


extern NSString *const HEWSSharingDataType_CALENDAR;

extern NSString *const HEWSSharingDataType_CONTACTS;
