// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class HEWSArrayOfStringsType;
@class HEWSNonEmptyArrayOfBaseItemIdsType;
@class HEWSItemIdType;
@class HEWSArrayOfItemClassType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSConversationType : NSObject <PicoBindable> {

@private
    HEWSItemIdType *_conversationId;
    NSString *_conversationTopic;
    HEWSArrayOfStringsType *_uniqueRecipients;
    HEWSArrayOfStringsType *_globalUniqueRecipients;
    HEWSArrayOfStringsType *_uniqueUnreadSenders;
    HEWSArrayOfStringsType *_globalUniqueUnreadSenders;
    HEWSArrayOfStringsType *_uniqueSenders;
    HEWSArrayOfStringsType *_globalUniqueSenders;
    NSDate *_lastDeliveryTime;
    NSDate *_globalLastDeliveryTime;
    HEWSArrayOfStringsType *_categories;
    HEWSArrayOfStringsType *_globalCategories;
    NSString *_flagStatus;
    NSString *_globalFlagStatus;
    NSNumber *_hasAttachments;
    NSNumber *_globalHasAttachments;
    NSNumber *_messageCount;
    NSNumber *_globalMessageCount;
    NSNumber *_unreadCount;
    NSNumber *_globalUnreadCount;
    NSNumber *_size;
    NSNumber *_globalSize;
    HEWSArrayOfItemClassType *_itemClasses;
    HEWSArrayOfItemClassType *_globalItemClasses;
    NSString *_importance;
    NSString *_globalImportance;
    HEWSNonEmptyArrayOfBaseItemIdsType *_itemIds;
    HEWSNonEmptyArrayOfBaseItemIdsType *_globalItemIds;

}


/**
 (public property)
 
 type : class HEWSItemIdType
*/
@property (nonatomic, retain) HEWSItemIdType *conversationId;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *conversationTopic;

/**
 (public property)
 
 type : class HEWSArrayOfStringsType
*/
@property (nonatomic, retain) HEWSArrayOfStringsType *uniqueRecipients;

/**
 (public property)
 
 type : class HEWSArrayOfStringsType
*/
@property (nonatomic, retain) HEWSArrayOfStringsType *globalUniqueRecipients;

/**
 (public property)
 
 type : class HEWSArrayOfStringsType
*/
@property (nonatomic, retain) HEWSArrayOfStringsType *uniqueUnreadSenders;

/**
 (public property)
 
 type : class HEWSArrayOfStringsType
*/
@property (nonatomic, retain) HEWSArrayOfStringsType *globalUniqueUnreadSenders;

/**
 (public property)
 
 type : class HEWSArrayOfStringsType
*/
@property (nonatomic, retain) HEWSArrayOfStringsType *uniqueSenders;

/**
 (public property)
 
 type : class HEWSArrayOfStringsType
*/
@property (nonatomic, retain) HEWSArrayOfStringsType *globalUniqueSenders;

/**
 (public property)
 
 type : NSDate, wrapper for primitive date
*/
@property (nonatomic, retain) NSDate *lastDeliveryTime;

/**
 (public property)
 
 type : NSDate, wrapper for primitive date
*/
@property (nonatomic, retain) NSDate *globalLastDeliveryTime;

/**
 (public property)
 
 type : class HEWSArrayOfStringsType
*/
@property (nonatomic, retain) HEWSArrayOfStringsType *categories;

/**
 (public property)
 
 type : class HEWSArrayOfStringsType
*/
@property (nonatomic, retain) HEWSArrayOfStringsType *globalCategories;

/**
 (public property)
 
 type: string constant in HEWSFlagStatusType.h
*/
@property (nonatomic, retain) NSString *flagStatus;

/**
 (public property)
 
 type: string constant in HEWSFlagStatusType.h
*/
@property (nonatomic, retain) NSString *globalFlagStatus;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *hasAttachments;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *globalHasAttachments;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *messageCount;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *globalMessageCount;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *unreadCount;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *globalUnreadCount;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *size;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *globalSize;

/**
 (public property)
 
 type : class HEWSArrayOfItemClassType
*/
@property (nonatomic, retain) HEWSArrayOfItemClassType *itemClasses;

/**
 (public property)
 
 type : class HEWSArrayOfItemClassType
*/
@property (nonatomic, retain) HEWSArrayOfItemClassType *globalItemClasses;

/**
 (public property)
 
 type: string constant in HEWSImportanceChoicesType.h
*/
@property (nonatomic, retain) NSString *importance;

/**
 (public property)
 
 type: string constant in HEWSImportanceChoicesType.h
*/
@property (nonatomic, retain) NSString *globalImportance;

/**
 (public property)
 
 type : class HEWSNonEmptyArrayOfBaseItemIdsType
*/
@property (nonatomic, retain) HEWSNonEmptyArrayOfBaseItemIdsType *itemIds;

/**
 (public property)
 
 type : class HEWSNonEmptyArrayOfBaseItemIdsType
*/
@property (nonatomic, retain) HEWSNonEmptyArrayOfBaseItemIdsType *globalItemIds;


@end
