// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>


extern NSString *const HEWSCreateActionType_CREATE_NEW;

extern NSString *const HEWSCreateActionType_UPDATE;

extern NSString *const HEWSCreateActionType_UPDATE_OR_CREATE;
