// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>


extern NSString *const HEWSMessageDispositionType_SAVE_ONLY;

extern NSString *const HEWSMessageDispositionType_SEND_ONLY;

extern NSString *const HEWSMessageDispositionType_SEND_AND_SAVE_COPY;
