// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "HEWSBaseGroupByType.h"



/**
 
         Allows consumers to access standard groupings for FindItem queries.  This is in
         contrast to the arbitrary (custom) groupings available via the t:GroupByType
       
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSDistinguishedGroupByType : HEWSBaseGroupByType {

@private
    NSString *_standardGroupBy;

}


/**
 (public property)
 
 type: string constant in HEWSStandardGroupByType.h
*/
@property (nonatomic, retain) NSString *standardGroupBy;


@end
