// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class HEWSBaseItemIdType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSNonEmptyArrayOfBaseItemIdsType : NSObject <PicoBindable> {

@private
    NSMutableArray *_itemIdOrOccurrenceItemIdOrRecurringMasterItemId;

}


/**
 (public property)
 
 entry type : class HEWSBaseItemIdType
*/

@property (nonatomic, retain) NSMutableArray *itemIdOrOccurrenceItemIdOrRecurringMasterItemId;


@end
