// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class HEWSEncryptedSharedFolderDataType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSArrayOfEncryptedSharedFolderDataType : NSObject <PicoBindable> {

@private
    NSMutableArray *_encryptedSharedFolderData;

}


/**
 (public property)
 
 entry type : class HEWSEncryptedSharedFolderDataType
*/

@property (nonatomic, retain) NSMutableArray *encryptedSharedFolderData;


@end
