// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"



/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSArrayOfTransitionsType : NSObject <PicoBindable> {

@private
    NSMutableArray *_transition;
    NSString *_id;

}


/**
 (public property)
 
 entry type : class HEWSJAXBElement<? extends TransitionType>
*/

@property (nonatomic, retain) NSMutableArray *transition;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *id;


@end
