// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import "HEWSMessageTrackingReportTemplateType.h"


NSString *const HEWSMessageTrackingReportTemplateType_SUMMARY = @"Summary";

NSString *const HEWSMessageTrackingReportTemplateType_RECIPIENT_PATH = @"RecipientPath";
