// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class HEWSEmailAddressDictionaryEntryType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSEmailAddressDictionaryType : NSObject <PicoBindable> {

@private
    NSMutableArray *_entry;

}


/**
 (public property)
 
 entry type : class HEWSEmailAddressDictionaryEntryType
*/

@property (nonatomic, retain) NSMutableArray *entry;


@end
