// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"



/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSSerializableTimeZoneTime : NSObject <PicoBindable> {

@private
    NSNumber *_bias;
    NSString *_time;
    NSNumber *_dayOrder;
    NSNumber *_month;
    NSString *_dayOfWeek;
    NSString *_year;

}


/**
 (public property)
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *bias;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *time;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive short
*/
@property (nonatomic, retain) NSNumber *dayOrder;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive short
*/
@property (nonatomic, retain) NSNumber *month;

/**
 (public property)
 
 type: string constant in HEWSDayOfWeekType.h
*/
@property (nonatomic, retain) NSString *dayOfWeek;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *year;


@end
