// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import "HEWSSensitivityChoicesType.h"


NSString *const HEWSSensitivityChoicesType_NORMAL = @"Normal";

NSString *const HEWSSensitivityChoicesType_PERSONAL = @"Personal";

NSString *const HEWSSensitivityChoicesType_PRIVATE = @"Private";

NSString *const HEWSSensitivityChoicesType_CONFIDENTIAL = @"Confidential";
