// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class HEWSContactItemType;
@class HEWSEmailAddressType;

/**
 (public class)
 
 @ingroup ExchangeServicePortType
*/
@interface HEWSResolutionType : NSObject <PicoBindable> {

@private
    HEWSEmailAddressType *_mailbox;
    HEWSContactItemType *_contact;

}


/**
 (public property)
 
 type : class HEWSEmailAddressType
*/
@property (nonatomic, retain) HEWSEmailAddressType *mailbox;

/**
 (public property)
 
 type : class HEWSContactItemType
*/
@property (nonatomic, retain) HEWSContactItemType *contact;


@end
