// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import "HEWSImAddressKeyType.h"


NSString *const HEWSImAddressKeyType_IM_ADDRESS_1 = @"ImAddress1";

NSString *const HEWSImAddressKeyType_IM_ADDRESS_2 = @"ImAddress2";

NSString *const HEWSImAddressKeyType_IM_ADDRESS_3 = @"ImAddress3";
