// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>


extern NSString *const HEWSPermissionLevelType_NONE;

extern NSString *const HEWSPermissionLevelType_OWNER;

extern NSString *const HEWSPermissionLevelType_PUBLISHING_EDITOR;

extern NSString *const HEWSPermissionLevelType_EDITOR;

extern NSString *const HEWSPermissionLevelType_PUBLISHING_AUTHOR;

extern NSString *const HEWSPermissionLevelType_AUTHOR;

extern NSString *const HEWSPermissionLevelType_NONEDITING_AUTHOR;

extern NSString *const HEWSPermissionLevelType_REVIEWER;

extern NSString *const HEWSPermissionLevelType_CONTRIBUTOR;

extern NSString *const HEWSPermissionLevelType_CUSTOM;
