// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "HEWSDeletedOccurrenceInfoType.h"

@implementation HEWSDeletedOccurrenceInfoType

@synthesize start = _start;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Start" propertyName:@"start" type:PICO_TYPE_DATE clazz:nil];
    [map setObject:ps forKey:@"start"];
    [ps release];
    
    return map;
}



-(void)dealloc {
    self.start = nil;
    [super dealloc];
}

@end
