// Generated by wsdl compiler for ios/objective-c
// DO NOT CHANGE!


#import <Foundation/Foundation.h>
#import "PicoXMLClient.h"
#import "HEWSSubscribeResponseType.h"
#import "HEWSGetItemType.h"
#import "HEWSFindItemType.h"
#import "HEWSRefreshSharingFolderType.h"
#import "HEWSMoveFolderResponseType.h"
#import "HEWSPlayOnPhoneResponseMessageType.h"
#import "HEWSCreateUserConfigurationResponseType.h"
#import "HEWSCopyFolderType.h"
#import "HEWSGetRoomsType.h"
#import "HEWSFindItemResponseType.h"
#import "HEWSCopyItemResponseType.h"
#import "HEWSGetDelegateResponseMessageType.h"
#import "HEWSDeleteItemResponseType.h"
#import "HEWSUnsubscribeType.h"
#import "HEWSCreateItemResponseType.h"
#import "HEWSGetPasswordExpirationDateResponseMessageType.h"
#import "HEWSDeleteUserConfigurationResponseType.h"
#import "HEWSMoveFolderType.h"
#import "HEWSApplyConversationActionType.h"
#import "HEWSRefreshSharingFolderResponseMessageType.h"
#import "HEWSCreateAttachmentType.h"
#import "HEWSGetPhoneCallInformationType.h"
#import "HEWSGetUserConfigurationResponseType.h"
#import "HEWSPlayOnPhoneType.h"
#import "HEWSGetAttachmentResponseType.h"
#import "HEWSGetSharingFolderType.h"
#import "HEWSGetItemResponseType.h"
#import "HEWSConvertIdResponseType.h"
#import "HEWSAddDelegateType.h"
#import "HEWSDeleteUserConfigurationType.h"
#import "HEWSExchangeImpersonationType.h"
#import "HEWSApplyConversationActionResponseType.h"
#import "HEWSExportItemsResponseType.h"
#import "HEWSGetPasswordExpirationDateType.h"
#import "HEWSResolveNamesResponseType.h"
#import "HEWSGetUserAvailabilityRequestType.h"
#import "HEWSSetUserOofSettingsResponse.h"
#import "HEWSEmptyFolderResponseType.h"
#import "HEWSSetUserOofSettingsRequest.h"
#import "HEWSCreateFolderResponseType.h"
#import "HEWSCopyFolderResponseType.h"
#import "HEWSSyncFolderItemsType.h"
#import "HEWSUploadItemsType.h"
#import "HEWSDeleteItemType.h"
#import "HEWSUpdateDelegateType.h"
#import "HEWSSyncFolderItemsResponseType.h"
#import "HEWSGetStreamingEventsResponseType.h"
#import "HEWSGetMessageTrackingReportResponseMessageType.h"
#import "HEWSUpdateItemResponseType.h"
#import "HEWSGetInboxRulesRequestType.h"
#import "HEWSExpandDLType.h"
#import "HEWSResolveNamesType.h"
#import "HEWSGetUserAvailabilityResponseType.h"
#import "HEWSCreateManagedFolderRequestType.h"
#import "HEWSFindConversationType.h"
#import "HEWSDisconnectPhoneCallResponseMessageType.h"
#import "HEWSvoid.h"
#import "HEWSGetEventsResponseType.h"
#import "HEWSGetServiceConfigurationType.h"
#import "HEWSDisconnectPhoneCallType.h"
#import "HEWSUpdateUserConfigurationResponseType.h"
#import "HEWSDeleteAttachmentType.h"
#import "HEWSRemoveDelegateType.h"
#import "HEWSUpdateDelegateResponseMessageType.h"
#import "HEWSGetEventsType.h"
#import "HEWSGetUserConfigurationType.h"
#import "HEWSSendItemType.h"
#import "HEWSGetSharingMetadataResponseMessageType.h"
#import "HEWSGetPhoneCallInformationResponseMessageType.h"
#import "HEWSFindFolderResponseType.h"
#import "HEWSCreateUserConfigurationType.h"
#import "HEWSMailboxCultureType.h"
#import "HEWSGetServerTimeZonesType.h"
#import "HEWSGetServerTimeZonesResponseType.h"
#import "HEWSMoveItemResponseType.h"
#import "HEWSExpandDLResponseType.h"
#import "HEWSCreateAttachmentResponseType.h"
#import "HEWSUpdateUserConfigurationType.h"
#import "HEWSGetRoomsResponseMessageType.h"
#import "HEWSUploadItemsResponseType.h"
#import "HEWSUpdateFolderType.h"
#import "HEWSSubscribeType.h"
#import "HEWSUpdateInboxRulesRequestType.h"
#import "HEWSCopyItemType.h"
#import "HEWSEmptyFolderType.h"
#import "HEWSGetFolderType.h"
#import "HEWSFindMessageTrackingReportResponseMessageType.h"
#import "HEWSCreateManagedFolderResponseType.h"
#import "HEWSDeleteFolderType.h"
#import "HEWSRemoveDelegateResponseMessageType.h"
#import "HEWSGetUserOofSettingsRequest.h"
#import "HEWSUpdateFolderResponseType.h"
#import "HEWSGetMessageTrackingReportRequestType.h"
#import "HEWSMoveItemType.h"
#import "HEWSGetRoomListsType.h"
#import "HEWSGetSharingMetadataType.h"
#import "HEWSServerVersionInfo.h"
#import "HEWSCreateFolderType.h"
#import "HEWSConvertIdType.h"
#import "HEWSTimeZoneContextType.h"
#import "HEWSCreateItemType.h"
#import "HEWSDeleteAttachmentResponseType.h"
#import "HEWSAddDelegateResponseMessageType.h"
#import "HEWSUpdateInboxRulesResponseType.h"
#import "HEWSRequestServerVersion.h"
#import "HEWSUpdateItemType.h"
#import "HEWSFindConversationResponseMessageType.h"
#import "HEWSGetStreamingEventsType.h"
#import "HEWSGetAttachmentType.h"
#import "HEWSGetRoomListsResponseMessageType.h"
#import "HEWSUnsubscribeResponseType.h"
#import "HEWSDeleteFolderResponseType.h"
#import "HEWSGetMailTipsType.h"
#import "HEWSSyncFolderHierarchyType.h"
#import "HEWSFindMessageTrackingReportRequestType.h"
#import "HEWSSyncFolderHierarchyResponseType.h"
#import "HEWSSendItemResponseType.h"
#import "HEWSGetInboxRulesResponseType.h"
#import "HEWSGetDelegateType.h"
#import "HEWSFindFolderType.h"
#import "HEWSGetFolderResponseType.h"
#import "HEWSGetMailTipsResponseMessageType.h"
#import "HEWSGetSharingFolderResponseMessageType.h"
#import "HEWSExportItemsType.h"
#import "HEWSGetUserOofSettingsResponse.h"
#import "HEWSGetServiceConfigurationResponseMessageType.h"
#import "HEWSDateTimePrecisionType.h"


/**
 This class is the XML client to the ExchangeServicePortType Web Service.
*/ 
@interface ExchangeServicePortType_XMLClient : PicoXMLClient {

}

/**
 public method
*/
-(void)resolveNames:(HEWSResolveNamesType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)expandDL:(HEWSExpandDLType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)getServerTimeZones:(HEWSGetServerTimeZonesType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)findFolder:(HEWSFindFolderType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)findItem:(HEWSFindItemType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)getFolder:(HEWSGetFolderType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)convertId:(HEWSConvertIdType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)uploadItems:(HEWSUploadItemsType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)exportItems:(HEWSExportItemsType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)createFolder:(HEWSCreateFolderType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)deleteFolder:(HEWSDeleteFolderType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)emptyFolder:(HEWSEmptyFolderType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)updateFolder:(HEWSUpdateFolderType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)moveFolder:(HEWSMoveFolderType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)copyFolder:(HEWSCopyFolderType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)subscribe:(HEWSSubscribeType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)unsubscribe:(HEWSUnsubscribeType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)getEvents:(HEWSGetEventsType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)getStreamingEvents:(HEWSGetStreamingEventsType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)syncFolderHierarchy:(HEWSSyncFolderHierarchyType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)syncFolderItems:(HEWSSyncFolderItemsType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)getItem:(HEWSGetItemType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)createItem:(HEWSCreateItemType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)deleteItem:(HEWSDeleteItemType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)updateItem:(HEWSUpdateItemType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)sendItem:(HEWSSendItemType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)moveItem:(HEWSMoveItemType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)copyItem:(HEWSCopyItemType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)createAttachment:(HEWSCreateAttachmentType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)deleteAttachment:(HEWSDeleteAttachmentType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)getAttachment:(HEWSGetAttachmentType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)createManagedFolder:(HEWSCreateManagedFolderRequestType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)getDelegate:(HEWSGetDelegateType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)addDelegate:(HEWSAddDelegateType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)removeDelegate:(HEWSRemoveDelegateType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)updateDelegate:(HEWSUpdateDelegateType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)createUserConfiguration:(HEWSCreateUserConfigurationType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)deleteUserConfiguration:(HEWSDeleteUserConfigurationType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)getUserConfiguration:(HEWSGetUserConfigurationType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)updateUserConfiguration:(HEWSUpdateUserConfigurationType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)getUserAvailability:(HEWSGetUserAvailabilityRequestType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)getUserOofSettings:(HEWSGetUserOofSettingsRequest *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)setUserOofSettings:(HEWSSetUserOofSettingsRequest *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)getServiceConfiguration:(HEWSGetServiceConfigurationType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)getMailTips:(HEWSGetMailTipsType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)playOnPhone:(HEWSPlayOnPhoneType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)getPhoneCallInformation:(HEWSGetPhoneCallInformationType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)disconnectPhoneCall:(HEWSDisconnectPhoneCallType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)getSharingMetadata:(HEWSGetSharingMetadataType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)refreshSharingFolder:(HEWSRefreshSharingFolderType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)getSharingFolder:(HEWSGetSharingFolderType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)getRoomLists:(HEWSGetRoomListsType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)getRooms:(HEWSGetRoomsType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)findMessageTrackingReport:(HEWSFindMessageTrackingReportRequestType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)getMessageTrackingReport:(HEWSGetMessageTrackingReportRequestType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)findConversation:(HEWSFindConversationType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)applyConversationAction:(HEWSApplyConversationActionType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)getInboxRules:(HEWSGetInboxRulesRequestType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)updateInboxRules:(HEWSUpdateInboxRulesRequestType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 public method
*/
-(void)getPasswordExpirationDate:(HEWSGetPasswordExpirationDateType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure;


@end