// Generated by wsdl compiler for ios/objective-c
// DO NOT CHANGE!


#import "ExchangeServicePortType_XMLClient.h"

@implementation ExchangeServicePortType_XMLClient

-(void)resolveNames:(HEWSResolveNamesType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)expandDL:(HEWSExpandDLType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)getServerTimeZones:(HEWSGetServerTimeZonesType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)findFolder:(HEWSFindFolderType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)findItem:(HEWSFindItemType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)getFolder:(HEWSGetFolderType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)convertId:(HEWSConvertIdType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)uploadItems:(HEWSUploadItemsType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)exportItems:(HEWSExportItemsType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)createFolder:(HEWSCreateFolderType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)deleteFolder:(HEWSDeleteFolderType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)emptyFolder:(HEWSEmptyFolderType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)updateFolder:(HEWSUpdateFolderType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)moveFolder:(HEWSMoveFolderType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)copyFolder:(HEWSCopyFolderType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)subscribe:(HEWSSubscribeType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)unsubscribe:(HEWSUnsubscribeType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)getEvents:(HEWSGetEventsType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)getStreamingEvents:(HEWSGetStreamingEventsType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)syncFolderHierarchy:(HEWSSyncFolderHierarchyType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)syncFolderItems:(HEWSSyncFolderItemsType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)getItem:(HEWSGetItemType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)createItem:(HEWSCreateItemType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)deleteItem:(HEWSDeleteItemType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)updateItem:(HEWSUpdateItemType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)sendItem:(HEWSSendItemType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)moveItem:(HEWSMoveItemType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)copyItem:(HEWSCopyItemType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)createAttachment:(HEWSCreateAttachmentType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)deleteAttachment:(HEWSDeleteAttachmentType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)getAttachment:(HEWSGetAttachmentType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)createManagedFolder:(HEWSCreateManagedFolderRequestType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)getDelegate:(HEWSGetDelegateType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)addDelegate:(HEWSAddDelegateType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)removeDelegate:(HEWSRemoveDelegateType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)updateDelegate:(HEWSUpdateDelegateType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)createUserConfiguration:(HEWSCreateUserConfigurationType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)deleteUserConfiguration:(HEWSDeleteUserConfigurationType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)getUserConfiguration:(HEWSGetUserConfigurationType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)updateUserConfiguration:(HEWSUpdateUserConfigurationType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)getUserAvailability:(HEWSGetUserAvailabilityRequestType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)getUserOofSettings:(HEWSGetUserOofSettingsRequest *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)setUserOofSettings:(HEWSSetUserOofSettingsRequest *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)getServiceConfiguration:(HEWSGetServiceConfigurationType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)getMailTips:(HEWSGetMailTipsType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)playOnPhone:(HEWSPlayOnPhoneType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)getPhoneCallInformation:(HEWSGetPhoneCallInformationType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)disconnectPhoneCall:(HEWSDisconnectPhoneCallType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)getSharingMetadata:(HEWSGetSharingMetadataType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)refreshSharingFolder:(HEWSRefreshSharingFolderType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)getSharingFolder:(HEWSGetSharingFolderType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)getRoomLists:(HEWSGetRoomListsType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)getRooms:(HEWSGetRoomsType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)findMessageTrackingReport:(HEWSFindMessageTrackingReportRequestType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)getMessageTrackingReport:(HEWSGetMessageTrackingReportRequestType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)findConversation:(HEWSFindConversationType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)applyConversationAction:(HEWSApplyConversationActionType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)getInboxRules:(HEWSGetInboxRulesRequestType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)updateInboxRules:(HEWSUpdateInboxRulesRequestType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)getPasswordExpirationDate:(HEWSGetPasswordExpirationDateType *) requestObject 
      success:(void (^)(HEWSvoid *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[HEWSvoid class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}


@end